<?xml version="1.0" encoding="utf-8"?><Database Name="UNMehta" Class="RecruitmentAdvertisementSourceMasterDetailsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.1.159.21,1433;Initial Catalog=UNMehta;User ID=sa" SettingsObjectName="Unmehta.WebPortal.Data.Properties.Settings" SettingsPropertyName="UNMehtaConnectionString1" Provider="System.Data.SqlClient" />
  <Function Name="dbo.GetAllAdvertisementSourceMasterActive" Method="GetAllAdvertisementSourceMasterActive">
    <ElementType Name="GetAllAdvertisementSourceMasterActiveResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AdvertisementName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertRecruitmentAdvertisementSourceMasterDetails" Method="InsertRecruitmentAdvertisementSourceMasterDetails">
    <Parameter Name="AddId" Parameter="addId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="EducationTypeId" Parameter="educationTypeId" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="InsertRecruitmentAdvertisementSourceMasterDetailsResult">
      <Column Name="RecId" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.RemoveRecruitmentAdvertisementSourceMasterDetailsByAddId" Method="RemoveRecruitmentAdvertisementSourceMasterDetailsByAddId">
    <Parameter Name="AddId" Parameter="addId" Type="System.Int64" DbType="BigInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetAllRecruitmentAdvertisementSourceMasterDetailsByAddId" Method="GetAllRecruitmentAdvertisementSourceMasterDetailsByAddId">
    <Parameter Name="AddId" Parameter="addId" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="GetAllRecruitmentAdvertisementSourceMasterDetailsByAddIdResult">
      <Column Name="AdvertisementSourceId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>