<?xml version="1.0" encoding="utf-8"?><Database Name="UNMehta" Class="AdminMenuLinkDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.1.159.21,1433;Initial Catalog=UNMehta;User ID=sa" SettingsObjectName="Unmehta.WebPortal.Data.Properties.Settings" SettingsPropertyName="UNMehtaConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.GetAdminMenuMasterById" Method="GetAdminMenuMasterById">
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="GetAdminMenuMasterByIdResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="MenuName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MenuUrl" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MenuRank" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.RemoveAdminMenuMaster" Method="RemoveAdminMenuMaster">
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(100)" />
    <ElementType Name="RemoveAdminMenuMasterResult">
      <Column Name="RecId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertOrUpdateAdminMenuMaster" Method="InsertOrUpdateAdminMenuMaster">
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="MenuName" Parameter="menuName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="MenuUrl" Parameter="menuUrl" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="ParentId" Parameter="parentId" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IPAddress" Parameter="iPAddress" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetAllAdminMenuMaster" Method="GetAllAdminMenuMaster">
    <ElementType Name="GetAllAdminMenuMasterResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="MenuName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MenuUrl" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParentName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MenuRank" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>