#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unmehta.WebPortal.Data.Rights
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="UNMehta")]
	public partial class ChatBoxMasterDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ChatBoxMasterDataContext() : 
				base(global::Unmehta.WebPortal.Data.Properties.Settings.Default.UNMehtaConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public ChatBoxMasterDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChatBoxMasterDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChatBoxMasterDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChatBoxMasterDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllChatBotDetails")]
		public ISingleResult<GetAllChatBotDetailsResult> GetAllChatBotDetails()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetAllChatBotDetailsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertChatBotDetails")]
		public int InsertChatBotDetails([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(MAX)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsSkipEmail", DbType="Bit")] System.Nullable<bool> isSkipEmail, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmailId", DbType="NVarChar(MAX)")] string emailId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="YouLocation", DbType="NVarChar(MAX)")] string youLocation, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Phone", DbType="NVarChar(MAX)")] string phone, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsSkipPastMedicalHistory", DbType="Bit")] System.Nullable<bool> isSkipPastMedicalHistory, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PastMedicalHistory", DbType="NVarChar(MAX)")] string pastMedicalHistory, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsSkipPresentMedicalHistory", DbType="Bit")] System.Nullable<bool> isSkipPresentMedicalHistory, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PresentMedicalHistory", DbType="NVarChar(MAX)")] string presentMedicalHistory, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="WriteQuery", DbType="NVarChar(MAX)")] string writeQuery, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IPAddress", DbType="NVarChar(MAX)")] string iPAddress)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, isSkipEmail, emailId, youLocation, phone, isSkipPastMedicalHistory, pastMedicalHistory, isSkipPresentMedicalHistory, presentMedicalHistory, writeQuery, iPAddress);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.RemoveChatBotDetails")]
		public int RemoveChatBotDetails([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class GetAllChatBotDetailsResult
	{
		
		private long _Id;
		
		private string _Name;
		
		private System.Nullable<bool> _IsSkipEmail;
		
		private string _EmailId;
		
		private string _YouLocation;
		
		private string _Phone;
		
		private System.Nullable<bool> _IsSkipPastMedicalHistory;
		
		private string _PastMedicalHistory;
		
		private System.Nullable<bool> _IsSkipPresentMedicalHistory;
		
		private string _PresentMedicalHistory;
		
		private string _WriteQuery;
		
		private string _IPAddress;
		
		private System.Nullable<System.DateTime> _EntryDate;
		
		private bool _IsDelete;
		
		public GetAllChatBotDetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSkipEmail", DbType="Bit")]
		public System.Nullable<bool> IsSkipEmail
		{
			get
			{
				return this._IsSkipEmail;
			}
			set
			{
				if ((this._IsSkipEmail != value))
				{
					this._IsSkipEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailId", DbType="NVarChar(MAX)")]
		public string EmailId
		{
			get
			{
				return this._EmailId;
			}
			set
			{
				if ((this._EmailId != value))
				{
					this._EmailId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YouLocation", DbType="NVarChar(MAX)")]
		public string YouLocation
		{
			get
			{
				return this._YouLocation;
			}
			set
			{
				if ((this._YouLocation != value))
				{
					this._YouLocation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(MAX)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this._Phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSkipPastMedicalHistory", DbType="Bit")]
		public System.Nullable<bool> IsSkipPastMedicalHistory
		{
			get
			{
				return this._IsSkipPastMedicalHistory;
			}
			set
			{
				if ((this._IsSkipPastMedicalHistory != value))
				{
					this._IsSkipPastMedicalHistory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PastMedicalHistory", DbType="NVarChar(MAX)")]
		public string PastMedicalHistory
		{
			get
			{
				return this._PastMedicalHistory;
			}
			set
			{
				if ((this._PastMedicalHistory != value))
				{
					this._PastMedicalHistory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSkipPresentMedicalHistory", DbType="Bit")]
		public System.Nullable<bool> IsSkipPresentMedicalHistory
		{
			get
			{
				return this._IsSkipPresentMedicalHistory;
			}
			set
			{
				if ((this._IsSkipPresentMedicalHistory != value))
				{
					this._IsSkipPresentMedicalHistory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PresentMedicalHistory", DbType="NVarChar(MAX)")]
		public string PresentMedicalHistory
		{
			get
			{
				return this._PresentMedicalHistory;
			}
			set
			{
				if ((this._PresentMedicalHistory != value))
				{
					this._PresentMedicalHistory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WriteQuery", DbType="NVarChar(MAX)")]
		public string WriteQuery
		{
			get
			{
				return this._WriteQuery;
			}
			set
			{
				if ((this._WriteQuery != value))
				{
					this._WriteQuery = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPAddress", DbType="NVarChar(MAX)")]
		public string IPAddress
		{
			get
			{
				return this._IPAddress;
			}
			set
			{
				if ((this._IPAddress != value))
				{
					this._IPAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EntryDate
		{
			get
			{
				return this._EntryDate;
			}
			set
			{
				if ((this._EntryDate != value))
				{
					this._EntryDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDelete", DbType="Bit NOT NULL")]
		public bool IsDelete
		{
			get
			{
				return this._IsDelete;
			}
			set
			{
				if ((this._IsDelete != value))
				{
					this._IsDelete = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
