#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unmehta.WebPortal.Data.Hospital
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="UNMehta")]
	public partial class CandidateBasicDetailsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public CandidateBasicDetailsDataContext() : 
				base(global::Unmehta.WebPortal.Data.Properties.Settings.Default.UNMehtaConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public CandidateBasicDetailsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CandidateBasicDetailsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CandidateBasicDetailsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CandidateBasicDetailsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllCandidateFamilyDetails")]
		public ISingleResult<GetAllCandidateFamilyDetailsResult> GetAllCandidateFamilyDetails()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetAllCandidateFamilyDetailsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetCandidateFamilyDetailsById")]
		public ISingleResult<GetCandidateFamilyDetailsByIdResult> GetCandidateFamilyDetailsById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<GetCandidateFamilyDetailsByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertOrUpdateCandidateFamilyDetails")]
		public ISingleResult<InsertOrUpdateCandidateFamilyDetailsResult> InsertOrUpdateCandidateFamilyDetails([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegisrationId", DbType="NVarChar(MAX)")] string regisrationId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CandidateId", DbType="BigInt")] System.Nullable<long> candidateId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MemberName", DbType="NVarChar(MAX)")] string memberName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Age", DbType="BigInt")] System.Nullable<long> age, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RelationId", DbType="BigInt")] System.Nullable<long> relationId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Occupation", DbType="NVarChar(MAX)")] string occupation, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MonthlyIncome", DbType="Decimal(18,2)")] System.Nullable<decimal> monthlyIncome, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsVisible", DbType="Bit")] System.Nullable<bool> isVisible, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="NVarChar(500)")] string userName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, regisrationId, candidateId, memberName, age, relationId, occupation, monthlyIncome, isVisible, userName);
			return ((ISingleResult<InsertOrUpdateCandidateFamilyDetailsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetCandidateDetailsById")]
		public ISingleResult<GetCandidateDetailsByIdResult> GetCandidateDetailsById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<GetCandidateDetailsByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateLock")]
		public ISingleResult<UpdateLockResult> UpdateLock([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CandId", DbType="BigInt")] System.Nullable<long> candId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="JobId", DbType="BigInt")] System.Nullable<long> jobId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="NVarChar(MAX)")] string userName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), candId, jobId, userName);
			return ((ISingleResult<UpdateLockResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllCandidateRecruitmentMaster")]
		public ISingleResult<GetAllCandidateRecruitmentMasterResult> GetAllCandidateRecruitmentMaster()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetAllCandidateRecruitmentMasterResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertOrUpdateCandidateDetails")]
		public ISingleResult<InsertOrUpdateCandidateDetailsResult> InsertOrUpdateCandidateDetails(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Advertisementid", DbType="BigInt")] System.Nullable<long> advertisementid, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegisrationId", DbType="NVarChar(MAX)")] string regisrationId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FirstName", DbType="NVarChar(MAX)")] string firstName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MiddleName", DbType="NVarChar(MAX)")] string middleName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastName", DbType="NVarChar(MAX)")] string lastName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AadharCard", DbType="NVarChar(MAX)")] string aadharCard, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MotherName", DbType="NVarChar(MAX)")] string motherName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateOfBirth", DbType="Date")] System.Nullable<System.DateTime> dateOfBirth, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Age", DbType="BigInt")] System.Nullable<long> age, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mobile", DbType="NVarChar(MAX)")] string mobile, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmailId", DbType="NVarChar(MAX)")] string emailId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParmenentAddress", DbType="NVarChar(MAX)")] string parmenentAddress, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParmenentPincode", DbType="NVarChar(MAX)")] string parmenentPincode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParmenentPhoneR", DbType="NVarChar(MAX)")] string parmenentPhoneR, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParmenentPhoneM", DbType="NVarChar(MAX)")] string parmenentPhoneM, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CountryCode", DbType="NVarChar(50)")] string countryCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParmenentCountry", DbType="NVarChar(MAX)")] string parmenentCountry, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParmenentState", DbType="NVarChar(MAX)")] string parmenentState, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParmenentCity", DbType="NVarChar(MAX)")] string parmenentCity, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PresentAddress", DbType="NVarChar(MAX)")] string presentAddress, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PresentPincode", DbType="NVarChar(MAX)")] string presentPincode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PresentPhoneR", DbType="NVarChar(MAX)")] string presentPhoneR, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PresentPhoneM", DbType="NVarChar(MAX)")] string presentPhoneM, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CountryCode1", DbType="NVarChar(50)")] string countryCode1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PresentCountry", DbType="NVarChar(MAX)")] string presentCountry, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PresentState", DbType="NVarChar(MAX)")] string presentState, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PresentCity", DbType="NVarChar(MAX)")] string presentCity, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CasteId", DbType="BigInt")] System.Nullable<long> casteId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gender", DbType="Int")] System.Nullable<int> gender, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Religion", DbType="NVarChar(MAX)")] string religion, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaritalStatus", DbType="NVarChar(MAX)")] string maritalStatus, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SpouseFirstName", DbType="NVarChar(MAX)")] string spouseFirstName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SpouseMiddleName", DbType="NVarChar(MAX)")] string spouseMiddleName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SpouseSurname", DbType="NVarChar(MAX)")] string spouseSurname, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SpouseDOB", DbType="Date")] System.Nullable<System.DateTime> spouseDOB, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SpouseContact", DbType="NVarChar(MAX)")] string spouseContact, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmergencyContactPersonName", DbType="NVarChar(MAX)")] string emergencyContactPersonName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmergencyContactNo", DbType="NVarChar(MAX)")] string emergencyContactNo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(MAX)")] string password, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PhotographName", DbType="NVarChar(MAX)")] string photographName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PhotographPath", DbType="NVarChar(MAX)")] string photographPath, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SignatureName", DbType="NVarChar(MAX)")] string signatureName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SignaturePath", DbType="NVarChar(MAX)")] string signaturePath, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="NVarChar(500)")] string userName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, advertisementid, regisrationId, firstName, middleName, lastName, aadharCard, motherName, dateOfBirth, age, mobile, emailId, parmenentAddress, parmenentPincode, parmenentPhoneR, parmenentPhoneM, countryCode, parmenentCountry, parmenentState, parmenentCity, presentAddress, presentPincode, presentPhoneR, presentPhoneM, countryCode1, presentCountry, presentState, presentCity, casteId, gender, religion, maritalStatus, spouseFirstName, spouseMiddleName, spouseSurname, spouseDOB, spouseContact, emergencyContactPersonName, emergencyContactNo, password, photographName, photographPath, signatureName, signaturePath, userName);
			return ((ISingleResult<InsertOrUpdateCandidateDetailsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllCandidateDetails")]
		public ISingleResult<GetAllCandidateDetailsResult> GetAllCandidateDetails()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetAllCandidateDetailsResult>)(result.ReturnValue));
		}
	}
	
	public partial class GetAllCandidateFamilyDetailsResult
	{
		
		private long _Id;
		
		private string _RegisrationId;
		
		private System.Nullable<long> _CandidateId;
		
		private string _MemberName;
		
		private System.Nullable<long> _Age;
		
		private System.Nullable<long> _RelationId;
		
		private string _Occupation;
		
		private System.Nullable<decimal> _MonthlyIncome;
		
		private System.Nullable<bool> _IsVisible;
		
		public GetAllCandidateFamilyDetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegisrationId", DbType="NVarChar(MAX)")]
		public string RegisrationId
		{
			get
			{
				return this._RegisrationId;
			}
			set
			{
				if ((this._RegisrationId != value))
				{
					this._RegisrationId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CandidateId", DbType="BigInt")]
		public System.Nullable<long> CandidateId
		{
			get
			{
				return this._CandidateId;
			}
			set
			{
				if ((this._CandidateId != value))
				{
					this._CandidateId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberName", DbType="NVarChar(MAX)")]
		public string MemberName
		{
			get
			{
				return this._MemberName;
			}
			set
			{
				if ((this._MemberName != value))
				{
					this._MemberName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="BigInt")]
		public System.Nullable<long> Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this._Age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelationId", DbType="BigInt")]
		public System.Nullable<long> RelationId
		{
			get
			{
				return this._RelationId;
			}
			set
			{
				if ((this._RelationId != value))
				{
					this._RelationId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Occupation", DbType="NVarChar(MAX)")]
		public string Occupation
		{
			get
			{
				return this._Occupation;
			}
			set
			{
				if ((this._Occupation != value))
				{
					this._Occupation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MonthlyIncome", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> MonthlyIncome
		{
			get
			{
				return this._MonthlyIncome;
			}
			set
			{
				if ((this._MonthlyIncome != value))
				{
					this._MonthlyIncome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsVisible", DbType="Bit")]
		public System.Nullable<bool> IsVisible
		{
			get
			{
				return this._IsVisible;
			}
			set
			{
				if ((this._IsVisible != value))
				{
					this._IsVisible = value;
				}
			}
		}
	}
	
	public partial class GetCandidateFamilyDetailsByIdResult
	{
		
		private long _Id;
		
		private string _RegisrationId;
		
		private System.Nullable<long> _CandidateId;
		
		private string _MemberName;
		
		private System.Nullable<long> _Age;
		
		private System.Nullable<long> _RelationId;
		
		private string _Occupation;
		
		private System.Nullable<decimal> _MonthlyIncome;
		
		private System.Nullable<bool> _IsVisible;
		
		private System.Nullable<bool> _IsDelete;
		
		public GetCandidateFamilyDetailsByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegisrationId", DbType="NVarChar(MAX)")]
		public string RegisrationId
		{
			get
			{
				return this._RegisrationId;
			}
			set
			{
				if ((this._RegisrationId != value))
				{
					this._RegisrationId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CandidateId", DbType="BigInt")]
		public System.Nullable<long> CandidateId
		{
			get
			{
				return this._CandidateId;
			}
			set
			{
				if ((this._CandidateId != value))
				{
					this._CandidateId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberName", DbType="NVarChar(MAX)")]
		public string MemberName
		{
			get
			{
				return this._MemberName;
			}
			set
			{
				if ((this._MemberName != value))
				{
					this._MemberName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="BigInt")]
		public System.Nullable<long> Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this._Age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelationId", DbType="BigInt")]
		public System.Nullable<long> RelationId
		{
			get
			{
				return this._RelationId;
			}
			set
			{
				if ((this._RelationId != value))
				{
					this._RelationId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Occupation", DbType="NVarChar(MAX)")]
		public string Occupation
		{
			get
			{
				return this._Occupation;
			}
			set
			{
				if ((this._Occupation != value))
				{
					this._Occupation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MonthlyIncome", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> MonthlyIncome
		{
			get
			{
				return this._MonthlyIncome;
			}
			set
			{
				if ((this._MonthlyIncome != value))
				{
					this._MonthlyIncome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsVisible", DbType="Bit")]
		public System.Nullable<bool> IsVisible
		{
			get
			{
				return this._IsVisible;
			}
			set
			{
				if ((this._IsVisible != value))
				{
					this._IsVisible = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDelete", DbType="Bit")]
		public System.Nullable<bool> IsDelete
		{
			get
			{
				return this._IsDelete;
			}
			set
			{
				if ((this._IsDelete != value))
				{
					this._IsDelete = value;
				}
			}
		}
	}
	
	public partial class InsertOrUpdateCandidateFamilyDetailsResult
	{
		
		private System.Nullable<long> _RecId;
		
		public InsertOrUpdateCandidateFamilyDetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecId", DbType="BigInt")]
		public System.Nullable<long> RecId
		{
			get
			{
				return this._RecId;
			}
			set
			{
				if ((this._RecId != value))
				{
					this._RecId = value;
				}
			}
		}
	}
	
	public partial class GetCandidateDetailsByIdResult
	{
		
		private long _Id;
		
		private System.Nullable<long> _Advertisementid;
		
		private string _RegisrationId;
		
		private string _FirstName;
		
		private string _MiddleName;
		
		private string _LastName;
		
		private string _AadharCard;
		
		private string _MotherName;
		
		private System.Nullable<System.DateTime> _DateOfBirth;
		
		private System.Nullable<long> _Age;
		
		private string _Mobile;
		
		private string _EmailId;
		
		private string _ParmenentAddress;
		
		private string _ParmenentPincode;
		
		private string _ParmenentCountry;
		
		private string _ParmenentState;
		
		private string _ParmenentCity;
		
		private string _ParmenentPhoneR;
		
		private string _ParmenentPhoneM;
		
		private string _PresentAddress;
		
		private string _PresentPincode;
		
		private string _PresentCountry;
		
		private string _PresentState;
		
		private string _PresentCity;
		
		private string _PresentPhoneR;
		
		private string _PresentPhoneM;
		
		private System.Nullable<long> _CasteId;
		
		private System.Nullable<int> _Gender;
		
		private string _Religion;
		
		private string _MaritalStatus;
		
		private string _SpouseFirstName;
		
		private string _SpouseMiddleName;
		
		private string _SpouseSurname;
		
		private System.Nullable<System.DateTime> _SpouseDOB;
		
		private string _SpouseContact;
		
		private string _EmergencyContactPersonName;
		
		private string _EmergencyContactNo;
		
		private string _UserPassword;
		
		private string _PhotographName;
		
		private string _PhotographPath;
		
		private string _SignatureName;
		
		private string _SignaturePath;
		
		private string _RoleInLastEmployment;
		
		private System.Nullable<decimal> _CurrentSalaryPerMonth;
		
		private System.Nullable<decimal> _ExpectedSalary;
		
		private string _ExtraActivities;
		
		private string _MemberShipOfAnySpecialBodies;
		
		private System.Nullable<bool> _HaveChronicIllness;
		
		private string _ChronicIllnessDetails;
		
		private System.Nullable<bool> _IsOffenceRegistered;
		
		private string _OffneceDetails;
		
		private string _DescribeYourself;
		
		private string _BiggestAchivement;
		
		private string _YourBiggestFailure;
		
		private string _VisionInNextYears;
		
		private string _Remarks;
		
		private string _AdvertisementAwarenessSource;
		
		private bool _IsDelete;
		
		public GetCandidateDetailsByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Advertisementid", DbType="BigInt")]
		public System.Nullable<long> Advertisementid
		{
			get
			{
				return this._Advertisementid;
			}
			set
			{
				if ((this._Advertisementid != value))
				{
					this._Advertisementid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegisrationId", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string RegisrationId
		{
			get
			{
				return this._RegisrationId;
			}
			set
			{
				if ((this._RegisrationId != value))
				{
					this._RegisrationId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(MAX)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="NVarChar(MAX)")]
		public string MiddleName
		{
			get
			{
				return this._MiddleName;
			}
			set
			{
				if ((this._MiddleName != value))
				{
					this._MiddleName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(MAX)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AadharCard", DbType="NVarChar(MAX)")]
		public string AadharCard
		{
			get
			{
				return this._AadharCard;
			}
			set
			{
				if ((this._AadharCard != value))
				{
					this._AadharCard = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotherName", DbType="NVarChar(MAX)")]
		public string MotherName
		{
			get
			{
				return this._MotherName;
			}
			set
			{
				if ((this._MotherName != value))
				{
					this._MotherName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfBirth", DbType="Date")]
		public System.Nullable<System.DateTime> DateOfBirth
		{
			get
			{
				return this._DateOfBirth;
			}
			set
			{
				if ((this._DateOfBirth != value))
				{
					this._DateOfBirth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="BigInt")]
		public System.Nullable<long> Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this._Age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="NVarChar(MAX)")]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this._Mobile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailId", DbType="NVarChar(MAX)")]
		public string EmailId
		{
			get
			{
				return this._EmailId;
			}
			set
			{
				if ((this._EmailId != value))
				{
					this._EmailId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParmenentAddress", DbType="NVarChar(MAX)")]
		public string ParmenentAddress
		{
			get
			{
				return this._ParmenentAddress;
			}
			set
			{
				if ((this._ParmenentAddress != value))
				{
					this._ParmenentAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParmenentPincode", DbType="NVarChar(MAX)")]
		public string ParmenentPincode
		{
			get
			{
				return this._ParmenentPincode;
			}
			set
			{
				if ((this._ParmenentPincode != value))
				{
					this._ParmenentPincode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParmenentCountry", DbType="NVarChar(MAX)")]
		public string ParmenentCountry
		{
			get
			{
				return this._ParmenentCountry;
			}
			set
			{
				if ((this._ParmenentCountry != value))
				{
					this._ParmenentCountry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParmenentState", DbType="NVarChar(MAX)")]
		public string ParmenentState
		{
			get
			{
				return this._ParmenentState;
			}
			set
			{
				if ((this._ParmenentState != value))
				{
					this._ParmenentState = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParmenentCity", DbType="NVarChar(MAX)")]
		public string ParmenentCity
		{
			get
			{
				return this._ParmenentCity;
			}
			set
			{
				if ((this._ParmenentCity != value))
				{
					this._ParmenentCity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParmenentPhoneR", DbType="NVarChar(MAX)")]
		public string ParmenentPhoneR
		{
			get
			{
				return this._ParmenentPhoneR;
			}
			set
			{
				if ((this._ParmenentPhoneR != value))
				{
					this._ParmenentPhoneR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParmenentPhoneM", DbType="NVarChar(MAX)")]
		public string ParmenentPhoneM
		{
			get
			{
				return this._ParmenentPhoneM;
			}
			set
			{
				if ((this._ParmenentPhoneM != value))
				{
					this._ParmenentPhoneM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PresentAddress", DbType="NVarChar(MAX)")]
		public string PresentAddress
		{
			get
			{
				return this._PresentAddress;
			}
			set
			{
				if ((this._PresentAddress != value))
				{
					this._PresentAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PresentPincode", DbType="NVarChar(MAX)")]
		public string PresentPincode
		{
			get
			{
				return this._PresentPincode;
			}
			set
			{
				if ((this._PresentPincode != value))
				{
					this._PresentPincode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PresentCountry", DbType="NVarChar(MAX)")]
		public string PresentCountry
		{
			get
			{
				return this._PresentCountry;
			}
			set
			{
				if ((this._PresentCountry != value))
				{
					this._PresentCountry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PresentState", DbType="NVarChar(MAX)")]
		public string PresentState
		{
			get
			{
				return this._PresentState;
			}
			set
			{
				if ((this._PresentState != value))
				{
					this._PresentState = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PresentCity", DbType="NVarChar(MAX)")]
		public string PresentCity
		{
			get
			{
				return this._PresentCity;
			}
			set
			{
				if ((this._PresentCity != value))
				{
					this._PresentCity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PresentPhoneR", DbType="NVarChar(MAX)")]
		public string PresentPhoneR
		{
			get
			{
				return this._PresentPhoneR;
			}
			set
			{
				if ((this._PresentPhoneR != value))
				{
					this._PresentPhoneR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PresentPhoneM", DbType="NVarChar(MAX)")]
		public string PresentPhoneM
		{
			get
			{
				return this._PresentPhoneM;
			}
			set
			{
				if ((this._PresentPhoneM != value))
				{
					this._PresentPhoneM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CasteId", DbType="BigInt")]
		public System.Nullable<long> CasteId
		{
			get
			{
				return this._CasteId;
			}
			set
			{
				if ((this._CasteId != value))
				{
					this._CasteId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="Int")]
		public System.Nullable<int> Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this._Gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Religion", DbType="NVarChar(MAX)")]
		public string Religion
		{
			get
			{
				return this._Religion;
			}
			set
			{
				if ((this._Religion != value))
				{
					this._Religion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaritalStatus", DbType="NVarChar(MAX)")]
		public string MaritalStatus
		{
			get
			{
				return this._MaritalStatus;
			}
			set
			{
				if ((this._MaritalStatus != value))
				{
					this._MaritalStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpouseFirstName", DbType="NVarChar(MAX)")]
		public string SpouseFirstName
		{
			get
			{
				return this._SpouseFirstName;
			}
			set
			{
				if ((this._SpouseFirstName != value))
				{
					this._SpouseFirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpouseMiddleName", DbType="NVarChar(MAX)")]
		public string SpouseMiddleName
		{
			get
			{
				return this._SpouseMiddleName;
			}
			set
			{
				if ((this._SpouseMiddleName != value))
				{
					this._SpouseMiddleName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpouseSurname", DbType="NVarChar(MAX)")]
		public string SpouseSurname
		{
			get
			{
				return this._SpouseSurname;
			}
			set
			{
				if ((this._SpouseSurname != value))
				{
					this._SpouseSurname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpouseDOB", DbType="Date")]
		public System.Nullable<System.DateTime> SpouseDOB
		{
			get
			{
				return this._SpouseDOB;
			}
			set
			{
				if ((this._SpouseDOB != value))
				{
					this._SpouseDOB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpouseContact", DbType="NVarChar(MAX)")]
		public string SpouseContact
		{
			get
			{
				return this._SpouseContact;
			}
			set
			{
				if ((this._SpouseContact != value))
				{
					this._SpouseContact = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmergencyContactPersonName", DbType="NVarChar(MAX)")]
		public string EmergencyContactPersonName
		{
			get
			{
				return this._EmergencyContactPersonName;
			}
			set
			{
				if ((this._EmergencyContactPersonName != value))
				{
					this._EmergencyContactPersonName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmergencyContactNo", DbType="NVarChar(MAX)")]
		public string EmergencyContactNo
		{
			get
			{
				return this._EmergencyContactNo;
			}
			set
			{
				if ((this._EmergencyContactNo != value))
				{
					this._EmergencyContactNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserPassword", DbType="NVarChar(MAX)")]
		public string UserPassword
		{
			get
			{
				return this._UserPassword;
			}
			set
			{
				if ((this._UserPassword != value))
				{
					this._UserPassword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhotographName", DbType="NVarChar(MAX)")]
		public string PhotographName
		{
			get
			{
				return this._PhotographName;
			}
			set
			{
				if ((this._PhotographName != value))
				{
					this._PhotographName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhotographPath", DbType="NVarChar(MAX)")]
		public string PhotographPath
		{
			get
			{
				return this._PhotographPath;
			}
			set
			{
				if ((this._PhotographPath != value))
				{
					this._PhotographPath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SignatureName", DbType="NVarChar(MAX)")]
		public string SignatureName
		{
			get
			{
				return this._SignatureName;
			}
			set
			{
				if ((this._SignatureName != value))
				{
					this._SignatureName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SignaturePath", DbType="NVarChar(MAX)")]
		public string SignaturePath
		{
			get
			{
				return this._SignaturePath;
			}
			set
			{
				if ((this._SignaturePath != value))
				{
					this._SignaturePath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleInLastEmployment", DbType="NVarChar(MAX)")]
		public string RoleInLastEmployment
		{
			get
			{
				return this._RoleInLastEmployment;
			}
			set
			{
				if ((this._RoleInLastEmployment != value))
				{
					this._RoleInLastEmployment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentSalaryPerMonth", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> CurrentSalaryPerMonth
		{
			get
			{
				return this._CurrentSalaryPerMonth;
			}
			set
			{
				if ((this._CurrentSalaryPerMonth != value))
				{
					this._CurrentSalaryPerMonth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpectedSalary", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> ExpectedSalary
		{
			get
			{
				return this._ExpectedSalary;
			}
			set
			{
				if ((this._ExpectedSalary != value))
				{
					this._ExpectedSalary = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtraActivities", DbType="NVarChar(MAX)")]
		public string ExtraActivities
		{
			get
			{
				return this._ExtraActivities;
			}
			set
			{
				if ((this._ExtraActivities != value))
				{
					this._ExtraActivities = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberShipOfAnySpecialBodies", DbType="NVarChar(MAX)")]
		public string MemberShipOfAnySpecialBodies
		{
			get
			{
				return this._MemberShipOfAnySpecialBodies;
			}
			set
			{
				if ((this._MemberShipOfAnySpecialBodies != value))
				{
					this._MemberShipOfAnySpecialBodies = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HaveChronicIllness", DbType="Bit")]
		public System.Nullable<bool> HaveChronicIllness
		{
			get
			{
				return this._HaveChronicIllness;
			}
			set
			{
				if ((this._HaveChronicIllness != value))
				{
					this._HaveChronicIllness = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChronicIllnessDetails", DbType="NVarChar(MAX)")]
		public string ChronicIllnessDetails
		{
			get
			{
				return this._ChronicIllnessDetails;
			}
			set
			{
				if ((this._ChronicIllnessDetails != value))
				{
					this._ChronicIllnessDetails = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsOffenceRegistered", DbType="Bit")]
		public System.Nullable<bool> IsOffenceRegistered
		{
			get
			{
				return this._IsOffenceRegistered;
			}
			set
			{
				if ((this._IsOffenceRegistered != value))
				{
					this._IsOffenceRegistered = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OffneceDetails", DbType="NVarChar(MAX)")]
		public string OffneceDetails
		{
			get
			{
				return this._OffneceDetails;
			}
			set
			{
				if ((this._OffneceDetails != value))
				{
					this._OffneceDetails = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescribeYourself", DbType="NVarChar(MAX)")]
		public string DescribeYourself
		{
			get
			{
				return this._DescribeYourself;
			}
			set
			{
				if ((this._DescribeYourself != value))
				{
					this._DescribeYourself = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BiggestAchivement", DbType="NVarChar(MAX)")]
		public string BiggestAchivement
		{
			get
			{
				return this._BiggestAchivement;
			}
			set
			{
				if ((this._BiggestAchivement != value))
				{
					this._BiggestAchivement = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YourBiggestFailure", DbType="NVarChar(MAX)")]
		public string YourBiggestFailure
		{
			get
			{
				return this._YourBiggestFailure;
			}
			set
			{
				if ((this._YourBiggestFailure != value))
				{
					this._YourBiggestFailure = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisionInNextYears", DbType="NVarChar(MAX)")]
		public string VisionInNextYears
		{
			get
			{
				return this._VisionInNextYears;
			}
			set
			{
				if ((this._VisionInNextYears != value))
				{
					this._VisionInNextYears = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="NVarChar(MAX)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this._Remarks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvertisementAwarenessSource", DbType="NVarChar(MAX)")]
		public string AdvertisementAwarenessSource
		{
			get
			{
				return this._AdvertisementAwarenessSource;
			}
			set
			{
				if ((this._AdvertisementAwarenessSource != value))
				{
					this._AdvertisementAwarenessSource = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDelete", DbType="Bit NOT NULL")]
		public bool IsDelete
		{
			get
			{
				return this._IsDelete;
			}
			set
			{
				if ((this._IsDelete != value))
				{
					this._IsDelete = value;
				}
			}
		}
	}
	
	public partial class UpdateLockResult
	{
		
		private string _Msg;
		
		public UpdateLockResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Msg", DbType="NVarChar(100)")]
		public string Msg
		{
			get
			{
				return this._Msg;
			}
			set
			{
				if ((this._Msg != value))
				{
					this._Msg = value;
				}
			}
		}
	}
	
	public partial class GetAllCandidateRecruitmentMasterResult
	{
		
		private long _Id;
		
		private string _RegisrationId;
		
		private System.Nullable<long> _Advertisementid;
		
		private string _PostName;
		
		private string _FullName;
		
		private string _MotherName;
		
		private string _GENDER;
		
		private string _DateOfBirth;
		
		private string _AadharCard;
		
		private System.Nullable<long> _Age;
		
		private string _Mobile;
		
		private string _EmailId;
		
		private System.Nullable<long> _CasteId;
		
		private string _CasteName;
		
		private string _Religion;
		
		private string _ReligionName;
		
		private string _MaritalStatus;
		
		private string _EmergencyContactPersonName;
		
		private string _UNMICRCContact;
		
		private string _EmergencyContactNo;
		
		private string _PhotographName;
		
		private string _PhotographPath;
		
		private string _SignatureName;
		
		private string _SignaturePath;
		
		private string _ParmenentAddress;
		
		private string _PresentAddress;
		
		private string _ParmenentPincode;
		
		private string _ParmenentCountry;
		
		private string _ParmenentState;
		
		private string _ParmenentCity;
		
		private string _PhotographPath1;
		
		private string _SignaturePath1;
		
		public GetAllCandidateRecruitmentMasterResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegisrationId", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string RegisrationId
		{
			get
			{
				return this._RegisrationId;
			}
			set
			{
				if ((this._RegisrationId != value))
				{
					this._RegisrationId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Advertisementid", DbType="BigInt")]
		public System.Nullable<long> Advertisementid
		{
			get
			{
				return this._Advertisementid;
			}
			set
			{
				if ((this._Advertisementid != value))
				{
					this._Advertisementid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostName", DbType="NVarChar(MAX)")]
		public string PostName
		{
			get
			{
				return this._PostName;
			}
			set
			{
				if ((this._PostName != value))
				{
					this._PostName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(MAX)")]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this._FullName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotherName", DbType="NVarChar(MAX)")]
		public string MotherName
		{
			get
			{
				return this._MotherName;
			}
			set
			{
				if ((this._MotherName != value))
				{
					this._MotherName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENDER", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string GENDER
		{
			get
			{
				return this._GENDER;
			}
			set
			{
				if ((this._GENDER != value))
				{
					this._GENDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfBirth", DbType="VarChar(30)")]
		public string DateOfBirth
		{
			get
			{
				return this._DateOfBirth;
			}
			set
			{
				if ((this._DateOfBirth != value))
				{
					this._DateOfBirth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AadharCard", DbType="NVarChar(MAX)")]
		public string AadharCard
		{
			get
			{
				return this._AadharCard;
			}
			set
			{
				if ((this._AadharCard != value))
				{
					this._AadharCard = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="BigInt")]
		public System.Nullable<long> Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this._Age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="NVarChar(MAX)")]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this._Mobile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailId", DbType="NVarChar(MAX)")]
		public string EmailId
		{
			get
			{
				return this._EmailId;
			}
			set
			{
				if ((this._EmailId != value))
				{
					this._EmailId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CasteId", DbType="BigInt")]
		public System.Nullable<long> CasteId
		{
			get
			{
				return this._CasteId;
			}
			set
			{
				if ((this._CasteId != value))
				{
					this._CasteId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CasteName", DbType="NVarChar(MAX)")]
		public string CasteName
		{
			get
			{
				return this._CasteName;
			}
			set
			{
				if ((this._CasteName != value))
				{
					this._CasteName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Religion", DbType="NVarChar(MAX)")]
		public string Religion
		{
			get
			{
				return this._Religion;
			}
			set
			{
				if ((this._Religion != value))
				{
					this._Religion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReligionName", DbType="NVarChar(MAX)")]
		public string ReligionName
		{
			get
			{
				return this._ReligionName;
			}
			set
			{
				if ((this._ReligionName != value))
				{
					this._ReligionName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaritalStatus", DbType="NVarChar(MAX)")]
		public string MaritalStatus
		{
			get
			{
				return this._MaritalStatus;
			}
			set
			{
				if ((this._MaritalStatus != value))
				{
					this._MaritalStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmergencyContactPersonName", DbType="NVarChar(MAX)")]
		public string EmergencyContactPersonName
		{
			get
			{
				return this._EmergencyContactPersonName;
			}
			set
			{
				if ((this._EmergencyContactPersonName != value))
				{
					this._EmergencyContactPersonName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNMICRCContact", DbType="NVarChar(MAX)")]
		public string UNMICRCContact
		{
			get
			{
				return this._UNMICRCContact;
			}
			set
			{
				if ((this._UNMICRCContact != value))
				{
					this._UNMICRCContact = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmergencyContactNo", DbType="NVarChar(MAX)")]
		public string EmergencyContactNo
		{
			get
			{
				return this._EmergencyContactNo;
			}
			set
			{
				if ((this._EmergencyContactNo != value))
				{
					this._EmergencyContactNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhotographName", DbType="NVarChar(MAX)")]
		public string PhotographName
		{
			get
			{
				return this._PhotographName;
			}
			set
			{
				if ((this._PhotographName != value))
				{
					this._PhotographName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhotographPath", DbType="NVarChar(MAX)")]
		public string PhotographPath
		{
			get
			{
				return this._PhotographPath;
			}
			set
			{
				if ((this._PhotographPath != value))
				{
					this._PhotographPath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SignatureName", DbType="NVarChar(MAX)")]
		public string SignatureName
		{
			get
			{
				return this._SignatureName;
			}
			set
			{
				if ((this._SignatureName != value))
				{
					this._SignatureName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SignaturePath", DbType="NVarChar(MAX)")]
		public string SignaturePath
		{
			get
			{
				return this._SignaturePath;
			}
			set
			{
				if ((this._SignaturePath != value))
				{
					this._SignaturePath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParmenentAddress", DbType="NVarChar(MAX)")]
		public string ParmenentAddress
		{
			get
			{
				return this._ParmenentAddress;
			}
			set
			{
				if ((this._ParmenentAddress != value))
				{
					this._ParmenentAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PresentAddress", DbType="NVarChar(MAX)")]
		public string PresentAddress
		{
			get
			{
				return this._PresentAddress;
			}
			set
			{
				if ((this._PresentAddress != value))
				{
					this._PresentAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParmenentPincode", DbType="NVarChar(MAX)")]
		public string ParmenentPincode
		{
			get
			{
				return this._ParmenentPincode;
			}
			set
			{
				if ((this._ParmenentPincode != value))
				{
					this._ParmenentPincode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParmenentCountry", DbType="NVarChar(MAX)")]
		public string ParmenentCountry
		{
			get
			{
				return this._ParmenentCountry;
			}
			set
			{
				if ((this._ParmenentCountry != value))
				{
					this._ParmenentCountry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParmenentState", DbType="NVarChar(MAX)")]
		public string ParmenentState
		{
			get
			{
				return this._ParmenentState;
			}
			set
			{
				if ((this._ParmenentState != value))
				{
					this._ParmenentState = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParmenentCity", DbType="NVarChar(MAX)")]
		public string ParmenentCity
		{
			get
			{
				return this._ParmenentCity;
			}
			set
			{
				if ((this._ParmenentCity != value))
				{
					this._ParmenentCity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhotographPath1", DbType="NVarChar(MAX)")]
		public string PhotographPath1
		{
			get
			{
				return this._PhotographPath1;
			}
			set
			{
				if ((this._PhotographPath1 != value))
				{
					this._PhotographPath1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SignaturePath1", DbType="NVarChar(MAX)")]
		public string SignaturePath1
		{
			get
			{
				return this._SignaturePath1;
			}
			set
			{
				if ((this._SignaturePath1 != value))
				{
					this._SignaturePath1 = value;
				}
			}
		}
	}
	
	public partial class InsertOrUpdateCandidateDetailsResult
	{
		
		private System.Nullable<long> _RecId;
		
		public InsertOrUpdateCandidateDetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecId", DbType="BigInt")]
		public System.Nullable<long> RecId
		{
			get
			{
				return this._RecId;
			}
			set
			{
				if ((this._RecId != value))
				{
					this._RecId = value;
				}
			}
		}
	}
	
	public partial class GetAllCandidateDetailsResult
	{
		
		private long _Id;
		
		private System.Nullable<long> _Advertisementid;
		
		private string _RegisrationId;
		
		private string _FirstName;
		
		private string _MiddleName;
		
		private string _LastName;
		
		private string _AadharCard;
		
		private string _MotherName;
		
		private System.Nullable<System.DateTime> _DateOfBirth;
		
		private System.Nullable<long> _Age;
		
		private string _Mobile;
		
		private string _EmailId;
		
		private System.Nullable<long> _CasteId;
		
		private System.Nullable<int> _Gender;
		
		private string _Religion;
		
		private string _MaritalStatus;
		
		private string _SpouseFirstName;
		
		private string _SpouseMiddleName;
		
		private string _SpouseSurname;
		
		private System.Nullable<System.DateTime> _SpouseDOB;
		
		private string _SpouseContact;
		
		private string _EmergencyContactPersonName;
		
		private string _UNMICRCContact;
		
		private string _EmergencyContactNo;
		
		private string _Password;
		
		private string _PhotographName;
		
		private string _PhotographPath;
		
		private string _SignatureName;
		
		private string _SignaturePath;
		
		private string _RoleInLastEmployment;
		
		private System.Nullable<decimal> _CurrentSalaryPerMonth;
		
		private System.Nullable<decimal> _ExpectedSalary;
		
		private string _ExtraActivities;
		
		private string _MemberShipOfAnySpecialBodies;
		
		private System.Nullable<bool> _HaveChronicIllness;
		
		private string _ChronicIllnessDetails;
		
		private System.Nullable<bool> _IsOffenceRegistered;
		
		private string _OffneceDetails;
		
		private string _DescribeYourself;
		
		private string _BiggestAchivement;
		
		private string _YourBiggestFailure;
		
		private string _VisionInNextYears;
		
		private string _Remarks;
		
		private string _AdvertisementAwarenessSource;
		
		private System.Nullable<bool> _IsFinalSubmit;
		
		private bool _IsDelete;
		
		private string _CreateBy;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _UpdateBy;
		
		private System.Nullable<System.DateTime> _UpdateDate;
		
		private string _DeleteBy;
		
		private System.Nullable<System.DateTime> _DeleteDate;
		
		private string _ParmenentAddress;
		
		private string _ParmenentPincode;
		
		private string _ParmenentCountry;
		
		private string _ParmenentState;
		
		private string _ParmenentCity;
		
		private string _ParmenentPhoneR;
		
		private string _ParmenentPhoneM;
		
		private string _PresentAddress;
		
		private string _PresentPincode;
		
		private string _PresentCountry;
		
		private string _PresentState;
		
		private string _PresentCity;
		
		private string _PresentPhoneR;
		
		private string _PresentPhoneM;
		
		private string _IndependentWorkWithResult;
		
		private string _WorkUnderSupervision;
		
		private string _ConferenceAttendanceAndPaper;
		
		private System.Nullable<bool> _IsBasicComputerLiteracy;
		
		private string _Other;
		
		private string _CountryCode;
		
		private string _CountryCode1;
		
		public GetAllCandidateDetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Advertisementid", DbType="BigInt")]
		public System.Nullable<long> Advertisementid
		{
			get
			{
				return this._Advertisementid;
			}
			set
			{
				if ((this._Advertisementid != value))
				{
					this._Advertisementid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegisrationId", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string RegisrationId
		{
			get
			{
				return this._RegisrationId;
			}
			set
			{
				if ((this._RegisrationId != value))
				{
					this._RegisrationId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(MAX)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="NVarChar(MAX)")]
		public string MiddleName
		{
			get
			{
				return this._MiddleName;
			}
			set
			{
				if ((this._MiddleName != value))
				{
					this._MiddleName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(MAX)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AadharCard", DbType="NVarChar(MAX)")]
		public string AadharCard
		{
			get
			{
				return this._AadharCard;
			}
			set
			{
				if ((this._AadharCard != value))
				{
					this._AadharCard = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotherName", DbType="NVarChar(MAX)")]
		public string MotherName
		{
			get
			{
				return this._MotherName;
			}
			set
			{
				if ((this._MotherName != value))
				{
					this._MotherName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfBirth", DbType="Date")]
		public System.Nullable<System.DateTime> DateOfBirth
		{
			get
			{
				return this._DateOfBirth;
			}
			set
			{
				if ((this._DateOfBirth != value))
				{
					this._DateOfBirth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="BigInt")]
		public System.Nullable<long> Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this._Age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="NVarChar(MAX)")]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this._Mobile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailId", DbType="NVarChar(MAX)")]
		public string EmailId
		{
			get
			{
				return this._EmailId;
			}
			set
			{
				if ((this._EmailId != value))
				{
					this._EmailId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CasteId", DbType="BigInt")]
		public System.Nullable<long> CasteId
		{
			get
			{
				return this._CasteId;
			}
			set
			{
				if ((this._CasteId != value))
				{
					this._CasteId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="Int")]
		public System.Nullable<int> Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this._Gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Religion", DbType="NVarChar(MAX)")]
		public string Religion
		{
			get
			{
				return this._Religion;
			}
			set
			{
				if ((this._Religion != value))
				{
					this._Religion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaritalStatus", DbType="NVarChar(MAX)")]
		public string MaritalStatus
		{
			get
			{
				return this._MaritalStatus;
			}
			set
			{
				if ((this._MaritalStatus != value))
				{
					this._MaritalStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpouseFirstName", DbType="NVarChar(MAX)")]
		public string SpouseFirstName
		{
			get
			{
				return this._SpouseFirstName;
			}
			set
			{
				if ((this._SpouseFirstName != value))
				{
					this._SpouseFirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpouseMiddleName", DbType="NVarChar(MAX)")]
		public string SpouseMiddleName
		{
			get
			{
				return this._SpouseMiddleName;
			}
			set
			{
				if ((this._SpouseMiddleName != value))
				{
					this._SpouseMiddleName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpouseSurname", DbType="NVarChar(MAX)")]
		public string SpouseSurname
		{
			get
			{
				return this._SpouseSurname;
			}
			set
			{
				if ((this._SpouseSurname != value))
				{
					this._SpouseSurname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpouseDOB", DbType="Date")]
		public System.Nullable<System.DateTime> SpouseDOB
		{
			get
			{
				return this._SpouseDOB;
			}
			set
			{
				if ((this._SpouseDOB != value))
				{
					this._SpouseDOB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpouseContact", DbType="NVarChar(MAX)")]
		public string SpouseContact
		{
			get
			{
				return this._SpouseContact;
			}
			set
			{
				if ((this._SpouseContact != value))
				{
					this._SpouseContact = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmergencyContactPersonName", DbType="NVarChar(MAX)")]
		public string EmergencyContactPersonName
		{
			get
			{
				return this._EmergencyContactPersonName;
			}
			set
			{
				if ((this._EmergencyContactPersonName != value))
				{
					this._EmergencyContactPersonName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNMICRCContact", DbType="NVarChar(MAX)")]
		public string UNMICRCContact
		{
			get
			{
				return this._UNMICRCContact;
			}
			set
			{
				if ((this._UNMICRCContact != value))
				{
					this._UNMICRCContact = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmergencyContactNo", DbType="NVarChar(MAX)")]
		public string EmergencyContactNo
		{
			get
			{
				return this._EmergencyContactNo;
			}
			set
			{
				if ((this._EmergencyContactNo != value))
				{
					this._EmergencyContactNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(MAX)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhotographName", DbType="NVarChar(MAX)")]
		public string PhotographName
		{
			get
			{
				return this._PhotographName;
			}
			set
			{
				if ((this._PhotographName != value))
				{
					this._PhotographName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhotographPath", DbType="NVarChar(MAX)")]
		public string PhotographPath
		{
			get
			{
				return this._PhotographPath;
			}
			set
			{
				if ((this._PhotographPath != value))
				{
					this._PhotographPath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SignatureName", DbType="NVarChar(MAX)")]
		public string SignatureName
		{
			get
			{
				return this._SignatureName;
			}
			set
			{
				if ((this._SignatureName != value))
				{
					this._SignatureName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SignaturePath", DbType="NVarChar(MAX)")]
		public string SignaturePath
		{
			get
			{
				return this._SignaturePath;
			}
			set
			{
				if ((this._SignaturePath != value))
				{
					this._SignaturePath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleInLastEmployment", DbType="NVarChar(MAX)")]
		public string RoleInLastEmployment
		{
			get
			{
				return this._RoleInLastEmployment;
			}
			set
			{
				if ((this._RoleInLastEmployment != value))
				{
					this._RoleInLastEmployment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentSalaryPerMonth", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> CurrentSalaryPerMonth
		{
			get
			{
				return this._CurrentSalaryPerMonth;
			}
			set
			{
				if ((this._CurrentSalaryPerMonth != value))
				{
					this._CurrentSalaryPerMonth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpectedSalary", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> ExpectedSalary
		{
			get
			{
				return this._ExpectedSalary;
			}
			set
			{
				if ((this._ExpectedSalary != value))
				{
					this._ExpectedSalary = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExtraActivities", DbType="NVarChar(MAX)")]
		public string ExtraActivities
		{
			get
			{
				return this._ExtraActivities;
			}
			set
			{
				if ((this._ExtraActivities != value))
				{
					this._ExtraActivities = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberShipOfAnySpecialBodies", DbType="NVarChar(MAX)")]
		public string MemberShipOfAnySpecialBodies
		{
			get
			{
				return this._MemberShipOfAnySpecialBodies;
			}
			set
			{
				if ((this._MemberShipOfAnySpecialBodies != value))
				{
					this._MemberShipOfAnySpecialBodies = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HaveChronicIllness", DbType="Bit")]
		public System.Nullable<bool> HaveChronicIllness
		{
			get
			{
				return this._HaveChronicIllness;
			}
			set
			{
				if ((this._HaveChronicIllness != value))
				{
					this._HaveChronicIllness = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChronicIllnessDetails", DbType="NVarChar(MAX)")]
		public string ChronicIllnessDetails
		{
			get
			{
				return this._ChronicIllnessDetails;
			}
			set
			{
				if ((this._ChronicIllnessDetails != value))
				{
					this._ChronicIllnessDetails = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsOffenceRegistered", DbType="Bit")]
		public System.Nullable<bool> IsOffenceRegistered
		{
			get
			{
				return this._IsOffenceRegistered;
			}
			set
			{
				if ((this._IsOffenceRegistered != value))
				{
					this._IsOffenceRegistered = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OffneceDetails", DbType="NVarChar(MAX)")]
		public string OffneceDetails
		{
			get
			{
				return this._OffneceDetails;
			}
			set
			{
				if ((this._OffneceDetails != value))
				{
					this._OffneceDetails = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescribeYourself", DbType="NVarChar(MAX)")]
		public string DescribeYourself
		{
			get
			{
				return this._DescribeYourself;
			}
			set
			{
				if ((this._DescribeYourself != value))
				{
					this._DescribeYourself = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BiggestAchivement", DbType="NVarChar(MAX)")]
		public string BiggestAchivement
		{
			get
			{
				return this._BiggestAchivement;
			}
			set
			{
				if ((this._BiggestAchivement != value))
				{
					this._BiggestAchivement = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YourBiggestFailure", DbType="NVarChar(MAX)")]
		public string YourBiggestFailure
		{
			get
			{
				return this._YourBiggestFailure;
			}
			set
			{
				if ((this._YourBiggestFailure != value))
				{
					this._YourBiggestFailure = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisionInNextYears", DbType="NVarChar(MAX)")]
		public string VisionInNextYears
		{
			get
			{
				return this._VisionInNextYears;
			}
			set
			{
				if ((this._VisionInNextYears != value))
				{
					this._VisionInNextYears = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="NVarChar(MAX)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this._Remarks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdvertisementAwarenessSource", DbType="NVarChar(MAX)")]
		public string AdvertisementAwarenessSource
		{
			get
			{
				return this._AdvertisementAwarenessSource;
			}
			set
			{
				if ((this._AdvertisementAwarenessSource != value))
				{
					this._AdvertisementAwarenessSource = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsFinalSubmit", DbType="Bit")]
		public System.Nullable<bool> IsFinalSubmit
		{
			get
			{
				return this._IsFinalSubmit;
			}
			set
			{
				if ((this._IsFinalSubmit != value))
				{
					this._IsFinalSubmit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDelete", DbType="Bit NOT NULL")]
		public bool IsDelete
		{
			get
			{
				return this._IsDelete;
			}
			set
			{
				if ((this._IsDelete != value))
				{
					this._IsDelete = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="NVarChar(100)")]
		public string CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this._CreateBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateBy", DbType="NVarChar(100)")]
		public string UpdateBy
		{
			get
			{
				return this._UpdateBy;
			}
			set
			{
				if ((this._UpdateBy != value))
				{
					this._UpdateBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this._UpdateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteBy", DbType="NVarChar(100)")]
		public string DeleteBy
		{
			get
			{
				return this._DeleteBy;
			}
			set
			{
				if ((this._DeleteBy != value))
				{
					this._DeleteBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeleteDate
		{
			get
			{
				return this._DeleteDate;
			}
			set
			{
				if ((this._DeleteDate != value))
				{
					this._DeleteDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParmenentAddress", DbType="NVarChar(MAX)")]
		public string ParmenentAddress
		{
			get
			{
				return this._ParmenentAddress;
			}
			set
			{
				if ((this._ParmenentAddress != value))
				{
					this._ParmenentAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParmenentPincode", DbType="NVarChar(MAX)")]
		public string ParmenentPincode
		{
			get
			{
				return this._ParmenentPincode;
			}
			set
			{
				if ((this._ParmenentPincode != value))
				{
					this._ParmenentPincode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParmenentCountry", DbType="NVarChar(MAX)")]
		public string ParmenentCountry
		{
			get
			{
				return this._ParmenentCountry;
			}
			set
			{
				if ((this._ParmenentCountry != value))
				{
					this._ParmenentCountry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParmenentState", DbType="NVarChar(MAX)")]
		public string ParmenentState
		{
			get
			{
				return this._ParmenentState;
			}
			set
			{
				if ((this._ParmenentState != value))
				{
					this._ParmenentState = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParmenentCity", DbType="NVarChar(MAX)")]
		public string ParmenentCity
		{
			get
			{
				return this._ParmenentCity;
			}
			set
			{
				if ((this._ParmenentCity != value))
				{
					this._ParmenentCity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParmenentPhoneR", DbType="NVarChar(MAX)")]
		public string ParmenentPhoneR
		{
			get
			{
				return this._ParmenentPhoneR;
			}
			set
			{
				if ((this._ParmenentPhoneR != value))
				{
					this._ParmenentPhoneR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParmenentPhoneM", DbType="NVarChar(MAX)")]
		public string ParmenentPhoneM
		{
			get
			{
				return this._ParmenentPhoneM;
			}
			set
			{
				if ((this._ParmenentPhoneM != value))
				{
					this._ParmenentPhoneM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PresentAddress", DbType="NVarChar(MAX)")]
		public string PresentAddress
		{
			get
			{
				return this._PresentAddress;
			}
			set
			{
				if ((this._PresentAddress != value))
				{
					this._PresentAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PresentPincode", DbType="NVarChar(MAX)")]
		public string PresentPincode
		{
			get
			{
				return this._PresentPincode;
			}
			set
			{
				if ((this._PresentPincode != value))
				{
					this._PresentPincode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PresentCountry", DbType="NVarChar(MAX)")]
		public string PresentCountry
		{
			get
			{
				return this._PresentCountry;
			}
			set
			{
				if ((this._PresentCountry != value))
				{
					this._PresentCountry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PresentState", DbType="NVarChar(MAX)")]
		public string PresentState
		{
			get
			{
				return this._PresentState;
			}
			set
			{
				if ((this._PresentState != value))
				{
					this._PresentState = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PresentCity", DbType="NVarChar(MAX)")]
		public string PresentCity
		{
			get
			{
				return this._PresentCity;
			}
			set
			{
				if ((this._PresentCity != value))
				{
					this._PresentCity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PresentPhoneR", DbType="NVarChar(MAX)")]
		public string PresentPhoneR
		{
			get
			{
				return this._PresentPhoneR;
			}
			set
			{
				if ((this._PresentPhoneR != value))
				{
					this._PresentPhoneR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PresentPhoneM", DbType="NVarChar(MAX)")]
		public string PresentPhoneM
		{
			get
			{
				return this._PresentPhoneM;
			}
			set
			{
				if ((this._PresentPhoneM != value))
				{
					this._PresentPhoneM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IndependentWorkWithResult", DbType="NVarChar(MAX)")]
		public string IndependentWorkWithResult
		{
			get
			{
				return this._IndependentWorkWithResult;
			}
			set
			{
				if ((this._IndependentWorkWithResult != value))
				{
					this._IndependentWorkWithResult = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkUnderSupervision", DbType="NVarChar(MAX)")]
		public string WorkUnderSupervision
		{
			get
			{
				return this._WorkUnderSupervision;
			}
			set
			{
				if ((this._WorkUnderSupervision != value))
				{
					this._WorkUnderSupervision = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConferenceAttendanceAndPaper", DbType="NVarChar(MAX)")]
		public string ConferenceAttendanceAndPaper
		{
			get
			{
				return this._ConferenceAttendanceAndPaper;
			}
			set
			{
				if ((this._ConferenceAttendanceAndPaper != value))
				{
					this._ConferenceAttendanceAndPaper = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsBasicComputerLiteracy", DbType="Bit")]
		public System.Nullable<bool> IsBasicComputerLiteracy
		{
			get
			{
				return this._IsBasicComputerLiteracy;
			}
			set
			{
				if ((this._IsBasicComputerLiteracy != value))
				{
					this._IsBasicComputerLiteracy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Other", DbType="NVarChar(MAX)")]
		public string Other
		{
			get
			{
				return this._Other;
			}
			set
			{
				if ((this._Other != value))
				{
					this._Other = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryCode", DbType="NVarChar(50)")]
		public string CountryCode
		{
			get
			{
				return this._CountryCode;
			}
			set
			{
				if ((this._CountryCode != value))
				{
					this._CountryCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryCode1", DbType="NVarChar(50)")]
		public string CountryCode1
		{
			get
			{
				return this._CountryCode1;
			}
			set
			{
				if ((this._CountryCode1 != value))
				{
					this._CountryCode1 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
