#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unmehta.WebPortal.Data.Hospital
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="UNMehta")]
	public partial class DailyEntryVisitMasterDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DailyEntryVisitMasterDataContext() : 
				base(global::Unmehta.WebPortal.Data.Properties.Settings.Default.UNMehtaConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public DailyEntryVisitMasterDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DailyEntryVisitMasterDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DailyEntryVisitMasterDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DailyEntryVisitMasterDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllDailyVisitCategoryMaster")]
		public ISingleResult<GetAllDailyVisitCategoryMasterResult> GetAllDailyVisitCategoryMaster()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetAllDailyVisitCategoryMasterResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.RemoveDailyEntryVisitMaster")]
		public int RemoveDailyEntryVisitMaster([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="NVarChar(MAX)")] string userName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, userName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.RemoveDailyVisitCategoryMaster")]
		public int RemoveDailyVisitCategoryMaster([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="NVarChar(MAX)")] string userName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, userName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertOrUpdateDailyVisitCategoryMaster")]
		public ISingleResult<InsertOrUpdateDailyVisitCategoryMasterResult> InsertOrUpdateDailyVisitCategoryMaster([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DailyCatagoryName", DbType="NVarChar(MAX)")] string dailyCatagoryName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="NVarChar(MAX)")] string userName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, dailyCatagoryName, userName);
			return ((ISingleResult<InsertOrUpdateDailyVisitCategoryMasterResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllDailyEntryVisitMaster")]
		public ISingleResult<GetAllDailyEntryVisitMasterResult> GetAllDailyEntryVisitMaster()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetAllDailyEntryVisitMasterResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertOrUpdateDailyEntryVisitMaster")]
		public ISingleResult<InsertOrUpdateDailyEntryVisitMasterResult> InsertOrUpdateDailyEntryVisitMaster([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DailyCatId", DbType="BigInt")] System.Nullable<long> dailyCatId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VisitCount", DbType="BigInt")] System.Nullable<long> visitCount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EntryName", DbType="NVarChar(MAX)")] string entryName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FileName", DbType="NVarChar(MAX)")] string fileName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PDFFileName", DbType="NVarChar(MAX)")] string pDFFileName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EntryDate", DbType="Date")] System.Nullable<System.DateTime> entryDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsVisable", DbType="Bit")] System.Nullable<bool> isVisable, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="NVarChar(MAX)")] string userName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, dailyCatId, visitCount, entryName, fileName, pDFFileName, entryDate, isVisable, userName);
			return ((ISingleResult<InsertOrUpdateDailyEntryVisitMasterResult>)(result.ReturnValue));
		}
	}
	
	public partial class GetAllDailyVisitCategoryMasterResult
	{
		
		private long _Id;
		
		private string _DailyCatagoryName;
		
		private System.Nullable<bool> _IsDelete;
		
		private string _CreateBy;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _UpdateBy;
		
		private System.Nullable<System.DateTime> _UpdateDate;
		
		private string _DeleteBy;
		
		private System.Nullable<System.DateTime> _DeleteDate;
		
		public GetAllDailyVisitCategoryMasterResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DailyCatagoryName", DbType="NVarChar(MAX)")]
		public string DailyCatagoryName
		{
			get
			{
				return this._DailyCatagoryName;
			}
			set
			{
				if ((this._DailyCatagoryName != value))
				{
					this._DailyCatagoryName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDelete", DbType="Bit")]
		public System.Nullable<bool> IsDelete
		{
			get
			{
				return this._IsDelete;
			}
			set
			{
				if ((this._IsDelete != value))
				{
					this._IsDelete = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="NVarChar(100)")]
		public string CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this._CreateBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateBy", DbType="NVarChar(100)")]
		public string UpdateBy
		{
			get
			{
				return this._UpdateBy;
			}
			set
			{
				if ((this._UpdateBy != value))
				{
					this._UpdateBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this._UpdateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteBy", DbType="NVarChar(100)")]
		public string DeleteBy
		{
			get
			{
				return this._DeleteBy;
			}
			set
			{
				if ((this._DeleteBy != value))
				{
					this._DeleteBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeleteDate
		{
			get
			{
				return this._DeleteDate;
			}
			set
			{
				if ((this._DeleteDate != value))
				{
					this._DeleteDate = value;
				}
			}
		}
	}
	
	public partial class InsertOrUpdateDailyVisitCategoryMasterResult
	{
		
		private System.Nullable<long> _RecId;
		
		public InsertOrUpdateDailyVisitCategoryMasterResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecId", DbType="BigInt")]
		public System.Nullable<long> RecId
		{
			get
			{
				return this._RecId;
			}
			set
			{
				if ((this._RecId != value))
				{
					this._RecId = value;
				}
			}
		}
	}
	
	public partial class GetAllDailyEntryVisitMasterResult
	{
		
		private long _Id;
		
		private System.Nullable<long> _DailyCatId;
		
		private string _EntryName;
		
		private string _FileName;
		
		private System.Nullable<long> _VisitCount;
		
		private string _PDFFileName;
		
		private System.Nullable<System.DateTime> _EntryDate;
		
		private System.Nullable<bool> _IsVisable;
		
		private bool _IsDelete;
		
		private string _CreateBy;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _UpdateBy;
		
		private System.Nullable<System.DateTime> _UpdateDate;
		
		private string _DeleteBy;
		
		private System.Nullable<System.DateTime> _DeleteDate;
		
		private string _DailyCatagoryName;
		
		public GetAllDailyEntryVisitMasterResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DailyCatId", DbType="BigInt")]
		public System.Nullable<long> DailyCatId
		{
			get
			{
				return this._DailyCatId;
			}
			set
			{
				if ((this._DailyCatId != value))
				{
					this._DailyCatId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryName", DbType="NVarChar(MAX)")]
		public string EntryName
		{
			get
			{
				return this._EntryName;
			}
			set
			{
				if ((this._EntryName != value))
				{
					this._EntryName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="NVarChar(MAX)")]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this._FileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisitCount", DbType="BigInt")]
		public System.Nullable<long> VisitCount
		{
			get
			{
				return this._VisitCount;
			}
			set
			{
				if ((this._VisitCount != value))
				{
					this._VisitCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PDFFileName", DbType="NVarChar(MAX)")]
		public string PDFFileName
		{
			get
			{
				return this._PDFFileName;
			}
			set
			{
				if ((this._PDFFileName != value))
				{
					this._PDFFileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryDate", DbType="Date")]
		public System.Nullable<System.DateTime> EntryDate
		{
			get
			{
				return this._EntryDate;
			}
			set
			{
				if ((this._EntryDate != value))
				{
					this._EntryDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsVisable", DbType="Bit")]
		public System.Nullable<bool> IsVisable
		{
			get
			{
				return this._IsVisable;
			}
			set
			{
				if ((this._IsVisable != value))
				{
					this._IsVisable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDelete", DbType="Bit NOT NULL")]
		public bool IsDelete
		{
			get
			{
				return this._IsDelete;
			}
			set
			{
				if ((this._IsDelete != value))
				{
					this._IsDelete = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="NVarChar(100)")]
		public string CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this._CreateBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateBy", DbType="NVarChar(100)")]
		public string UpdateBy
		{
			get
			{
				return this._UpdateBy;
			}
			set
			{
				if ((this._UpdateBy != value))
				{
					this._UpdateBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this._UpdateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteBy", DbType="NVarChar(100)")]
		public string DeleteBy
		{
			get
			{
				return this._DeleteBy;
			}
			set
			{
				if ((this._DeleteBy != value))
				{
					this._DeleteBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeleteDate
		{
			get
			{
				return this._DeleteDate;
			}
			set
			{
				if ((this._DeleteDate != value))
				{
					this._DeleteDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DailyCatagoryName", DbType="NVarChar(MAX)")]
		public string DailyCatagoryName
		{
			get
			{
				return this._DailyCatagoryName;
			}
			set
			{
				if ((this._DailyCatagoryName != value))
				{
					this._DailyCatagoryName = value;
				}
			}
		}
	}
	
	public partial class InsertOrUpdateDailyEntryVisitMasterResult
	{
		
		private System.Nullable<long> _RecId;
		
		public InsertOrUpdateDailyEntryVisitMasterResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecId", DbType="BigInt")]
		public System.Nullable<long> RecId
		{
			get
			{
				return this._RecId;
			}
			set
			{
				if ((this._RecId != value))
				{
					this._RecId = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
