<?xml version="1.0" encoding="utf-8"?><Database Name="UNMehta" Class="DepartmentTabDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-B7AUVFOV;Initial Catalog=UNMehta;Integrated Security=True" SettingsObjectName="Unmehta.WebPortal.Data.Properties.Settings" SettingsPropertyName="UNMehtaConnectionString5" Provider="System.Data.SqlClient" />
  <Function Name="dbo.GetAllDepartmentTabType" Method="GetAllDepartmentTabType">
    <ElementType Name="GetAllDepartmentTabTypeResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TabTypeName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TabType" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsHaveSub" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.RemoveDeparmentTabDetails" Method="RemoveDeparmentTabDetails">
    <Parameter Name="TabId" Parameter="tabId" Type="System.Int64" DbType="BigInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.RemoveDepartmentTabListMaster" Method="RemoveDepartmentTabListMaster">
    <Parameter Name="TabId" Parameter="tabId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="username" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertOrUpdateDepartmentTabListMaster" Method="InsertOrUpdateDepartmentTabListMaster">
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="OurExcId" Parameter="ourExcId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="LanguageId" Parameter="languageId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="DepartmentId" Parameter="departmentId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="ParentTabId" Parameter="parentTabId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="TabTypeId" Parameter="tabTypeId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="TabName" Parameter="tabName" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="SequanceNo" Parameter="sequanceNo" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="IsVisable" Parameter="isVisable" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="InsertOrUpdateDepartmentTabListMasterResult">
      <Column Name="RecId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAllDepartmentTabListMasterOurExcIdAndLangId" Method="GetAllDepartmentTabListMasterOurExcIdAndLangId">
    <Parameter Name="OurExcId" Parameter="ourExcId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="LangId" Parameter="langId" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="GetAllDepartmentTabListMasterOurExcIdAndLangIdResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="OurExcId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="LanguageId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="DepartmentId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ParentTabId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="TabTypeId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="TabName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SequanceNo" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="IsVisable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDelete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateBy" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeleteBy" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DeleteDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ParentTabName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TabTypeName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAllDeparmentTabDetailsTabId" Method="GetAllDeparmentTabDetailsTabId">
    <Parameter Name="TabId" Parameter="tabId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="LanguageId" Parameter="languageId" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="GetAllDeparmentTabDetailsTabIdResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="LanguageId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="TabId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="TabTypeId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SequanceNo" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="IntroductionDesc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PopupImageName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PopupBasicShortDesc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PopupDesc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ParentTabId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="StatasticId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="FacultyId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="IsVisable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDelete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateBy" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeleteBy" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DeleteDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TabTypeName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertOrUpdateDeparmentTabDetails" Method="InsertOrUpdateDeparmentTabDetails">
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="TabId" Parameter="tabId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="TabTypeId" Parameter="tabTypeId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="LanguageId" Parameter="languageId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="SequanceNo" Parameter="sequanceNo" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="IntroductionDesc" Parameter="introductionDesc" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="PopupImageName" Parameter="popupImageName" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="PopupBasicShortDesc" Parameter="popupBasicShortDesc" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="PopupDesc" Parameter="popupDesc" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="ParentTabId" Parameter="parentTabId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="StatasticId" Parameter="statasticId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="FacultyId" Parameter="facultyId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="IsVisable" Parameter="isVisable" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="InsertOrUpdateDeparmentTabDetailsResult">
      <Column Name="RecId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>