#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unmehta.WebPortal.Data.Hospital
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="UNMehta")]
	public partial class PatientsEducationBrochureDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public PatientsEducationBrochureDataContext() : 
				base(global::Unmehta.WebPortal.Data.Properties.Settings.Default.UNMehtaConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public PatientsEducationBrochureDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PatientsEducationBrochureDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PatientsEducationBrochureDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PatientsEducationBrochureDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.RemovePatientsEducationBrochure")]
		public int RemovePatientsEducationBrochure([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="NVarChar(MAX)")] string username)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, username);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllPatientsEducationBrochureMaster")]
		public ISingleResult<GetAllPatientsEducationBrochureMasterResult> GetAllPatientsEducationBrochureMaster([global::System.Data.Linq.Mapping.ParameterAttribute(Name="LangId", DbType="BigInt")] System.Nullable<long> langId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), langId);
			return ((ISingleResult<GetAllPatientsEducationBrochureMasterResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertOrUpdatePatientsEducationBrochureMaster")]
		public ISingleResult<InsertOrUpdatePatientsEducationBrochureMasterResult> InsertOrUpdatePatientsEducationBrochureMaster([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LangId", DbType="BigInt")] System.Nullable<long> langId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SequanceNo", DbType="BigInt")] System.Nullable<long> sequanceNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(MAX)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FrontImage", DbType="NVarChar(MAX)")] string frontImage, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pdf", DbType="NVarChar(MAX)")] string pdf, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsAvailable", DbType="Bit")] System.Nullable<bool> isAvailable, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="NVarChar(100)")] string userName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, langId, sequanceNo, name, frontImage, pdf, isAvailable, userName);
			return ((ISingleResult<InsertOrUpdatePatientsEducationBrochureMasterResult>)(result.ReturnValue));
		}
	}
	
	public partial class GetAllPatientsEducationBrochureMasterResult
	{
		
		private long _Id;
		
		private string _Name;
		
		private string _FrontImage;
		
		private string _FrontImagePath;
		
		private string _Pdf;
		
		private string _PdfPath;
		
		private System.Nullable<long> _SequanceNo;
		
		private System.Nullable<bool> _IsAvailable;
		
		public GetAllPatientsEducationBrochureMasterResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FrontImage", DbType="NVarChar(MAX)")]
		public string FrontImage
		{
			get
			{
				return this._FrontImage;
			}
			set
			{
				if ((this._FrontImage != value))
				{
					this._FrontImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FrontImagePath", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string FrontImagePath
		{
			get
			{
				return this._FrontImagePath;
			}
			set
			{
				if ((this._FrontImagePath != value))
				{
					this._FrontImagePath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pdf", DbType="NVarChar(MAX)")]
		public string Pdf
		{
			get
			{
				return this._Pdf;
			}
			set
			{
				if ((this._Pdf != value))
				{
					this._Pdf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PdfPath", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string PdfPath
		{
			get
			{
				return this._PdfPath;
			}
			set
			{
				if ((this._PdfPath != value))
				{
					this._PdfPath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SequanceNo", DbType="BigInt")]
		public System.Nullable<long> SequanceNo
		{
			get
			{
				return this._SequanceNo;
			}
			set
			{
				if ((this._SequanceNo != value))
				{
					this._SequanceNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAvailable", DbType="Bit")]
		public System.Nullable<bool> IsAvailable
		{
			get
			{
				return this._IsAvailable;
			}
			set
			{
				if ((this._IsAvailable != value))
				{
					this._IsAvailable = value;
				}
			}
		}
	}
	
	public partial class InsertOrUpdatePatientsEducationBrochureMasterResult
	{
		
		private System.Nullable<long> _RecId;
		
		public InsertOrUpdatePatientsEducationBrochureMasterResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecId", DbType="BigInt")]
		public System.Nullable<long> RecId
		{
			get
			{
				return this._RecId;
			}
			set
			{
				if ((this._RecId != value))
				{
					this._RecId = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
