<?xml version="1.0" encoding="utf-8"?><Database Name="UNMehta" Class="PatientsEducationBrochureDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.1.159.21,1433;Initial Catalog=UNMehta;User ID=sa" SettingsObjectName="Unmehta.WebPortal.Data.Properties.Settings" SettingsPropertyName="UNMehtaConnectionString1" Provider="System.Data.SqlClient" />
  <Function Name="dbo.RemovePatientsEducationBrochure" Method="RemovePatientsEducationBrochure">
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetAllPatientsEducationBrochureMaster" Method="GetAllPatientsEducationBrochureMaster">
    <Parameter Name="LangId" Parameter="langId" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="GetAllPatientsEducationBrochureMasterResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FrontImage" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FrontImagePath" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Pdf" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PdfPath" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="SequanceNo" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="IsAvailable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertOrUpdatePatientsEducationBrochureMaster" Method="InsertOrUpdatePatientsEducationBrochureMaster">
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="LangId" Parameter="langId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="SequanceNo" Parameter="sequanceNo" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="FrontImage" Parameter="frontImage" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Pdf" Parameter="pdf" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="IsAvailable" Parameter="isAvailable" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(100)" />
    <ElementType Name="InsertOrUpdatePatientsEducationBrochureMasterResult">
      <Column Name="RecId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>