<?xml version="1.0" encoding="utf-8"?><Database Name="UNMehta" Class="SpecializationMasterDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.1.159.21,1433;Initial Catalog=UNMehta;User ID=sa" SettingsObjectName="Unmehta.WebPortal.Data.Properties.Settings" SettingsPropertyName="UNMehtaConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.GetAllSpecializationMasterGrid" Method="GetAllSpecializationMasterGrid">
    <ElementType Name="GetAllSpecializationMasterGridResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAllSpecializationMaster" Method="GetAllSpecializationMaster">
    <ElementType Name="GetAllSpecializationMasterResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsSunday" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SunStartTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SunStartTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SunStartTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SunEndTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SunEndTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SunEndTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SunLaunchStartTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SunLaunchStartTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SunLaunchStartTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SunLaunchEndTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SunLaunchEndTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SunLaunchEndTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="IsMonday" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MonStartTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="MonStartTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="MonStartTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="MonEndTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="MonEndTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="MonEndTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="MonLaunchStartTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="MonLaunchStartTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="MonLaunchStartTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="MonLaunchEndTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="MonLaunchEndTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="MonLaunchEndTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="IsTuesday" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TueStartTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="TueStartTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="TueStartTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="TueEndTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="TueEndTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="TueEndTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="TueLaunchStartTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="TueLaunchStartTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="TueLaunchStartTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="TueLaunchEndTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="TueLaunchEndTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="TueLaunchEndTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="IsWednesday" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="WenStartTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="WenStartTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="WenStartTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="WenEndTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="WenEndTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="WenEndTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="WenLaunchStartTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="WenLaunchStartTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="WenLaunchStartTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="WenLaunchEndTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="WenLaunchEndTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="WenLaunchEndTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="IsThursday" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ThuStartTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ThuStartTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ThuStartTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ThuEndTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ThuEndTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ThuEndTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ThuLaunchStartTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ThuLaunchStartTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ThuLaunchStartTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ThuLaunchEndTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ThuLaunchEndTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ThuLaunchEndTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="IsFriday" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FriStartTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="FriStartTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="FriStartTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="FriEndTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="FriEndTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="FriEndTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="FriLaunchStartTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="FriLaunchStartTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="FriLaunchStartTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="FriLaunchEndTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="FriLaunchEndTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="FriLaunchEndTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="IsSaturday" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SatStartTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SatStartTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SatStartTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SatEndTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SatEndTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SatEndTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SatLaunchStartTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SatLaunchStartTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SatLaunchStartTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SatLaunchEndTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SatLaunchEndTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SatLaunchEndTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetSpecializationMasterById" Method="GetSpecializationMasterById">
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="GetSpecializationMasterByIdResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Interval" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsSunday" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SunStartTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SunStartTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SunStartTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SunEndTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SunEndTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SunEndTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SunLaunchStartTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SunLaunchStartTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SunLaunchStartTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SunLaunchEndTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SunLaunchEndTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SunLaunchEndTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="IsMonday" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MonStartTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="MonStartTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="MonStartTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="MonEndTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="MonEndTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="MonEndTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="MonLaunchStartTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="MonLaunchStartTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="MonLaunchStartTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="MonLaunchEndTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="MonLaunchEndTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="MonLaunchEndTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="IsTuesday" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TueStartTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="TueStartTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="TueStartTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="TueEndTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="TueEndTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="TueEndTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="TueLaunchStartTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="TueLaunchStartTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="TueLaunchStartTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="TueLaunchEndTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="TueLaunchEndTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="TueLaunchEndTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="IsWednesday" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="WenStartTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="WenStartTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="WenStartTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="WenEndTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="WenEndTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="WenEndTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="WenLaunchStartTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="WenLaunchStartTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="WenLaunchStartTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="WenLaunchEndTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="WenLaunchEndTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="WenLaunchEndTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="IsThursday" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ThuStartTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ThuStartTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ThuStartTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ThuEndTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ThuEndTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ThuEndTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ThuLaunchStartTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ThuLaunchStartTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ThuLaunchStartTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ThuLaunchEndTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ThuLaunchEndTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ThuLaunchEndTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="IsFriday" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FriStartTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="FriStartTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="FriStartTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="FriEndTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="FriEndTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="FriEndTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="FriLaunchStartTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="FriLaunchStartTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="FriLaunchStartTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="FriLaunchEndTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="FriLaunchEndTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="FriLaunchEndTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="IsSaturday" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SatStartTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SatStartTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SatStartTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SatEndTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SatEndTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SatEndTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SatLaunchStartTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SatLaunchStartTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SatLaunchStartTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SatLaunchEndTimeHour" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SatLaunchEndTimeMin" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="SatLaunchEndTimeTT" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertOrUpdateSpecializationMaster" Method="InsertOrUpdateSpecializationMaster">
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="DepartmentName" Parameter="departmentName" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="InsertOrUpdateSpecializationMasterResult">
      <Column Name="RecId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.RemoveSpecializationMaster" Method="RemoveSpecializationMaster">
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateSpecializationMasterSchedule" Method="UpdateSpecializationMasterSchedule">
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Interval" Parameter="interval" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsSunday" Parameter="isSunday" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="SunStartTimeHour" Parameter="sunStartTimeHour" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="SunStartTimeMin" Parameter="sunStartTimeMin" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="SunStartTimeTT" Parameter="sunStartTimeTT" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="SunEndTimeHour" Parameter="sunEndTimeHour" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="SunEndTimeMin" Parameter="sunEndTimeMin" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="SunEndTimeTT" Parameter="sunEndTimeTT" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="SunLaunchStartTimeHour" Parameter="sunLaunchStartTimeHour" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="SunLaunchStartTimeMin" Parameter="sunLaunchStartTimeMin" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="SunLaunchStartTimeTT" Parameter="sunLaunchStartTimeTT" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="SunLaunchEndTimeHour" Parameter="sunLaunchEndTimeHour" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="SunLaunchEndTimeMin" Parameter="sunLaunchEndTimeMin" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="SunLaunchEndTimeTT" Parameter="sunLaunchEndTimeTT" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="IsMonday" Parameter="isMonday" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="MonStartTimeHour" Parameter="monStartTimeHour" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="MonStartTimeMin" Parameter="monStartTimeMin" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="MonStartTimeTT" Parameter="monStartTimeTT" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="MonEndTimeHour" Parameter="monEndTimeHour" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="MonEndTimeMin" Parameter="monEndTimeMin" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="MonEndTimeTT" Parameter="monEndTimeTT" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="MonLaunchStartTimeHour" Parameter="monLaunchStartTimeHour" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="MonLaunchStartTimeMin" Parameter="monLaunchStartTimeMin" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="MonLaunchStartTimeTT" Parameter="monLaunchStartTimeTT" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="MonLaunchEndTimeHour" Parameter="monLaunchEndTimeHour" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="MonLaunchEndTimeMin" Parameter="monLaunchEndTimeMin" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="MonLaunchEndTimeTT" Parameter="monLaunchEndTimeTT" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="IsTuesday" Parameter="isTuesday" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="TueStartTimeHour" Parameter="tueStartTimeHour" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="TueStartTimeMin" Parameter="tueStartTimeMin" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="TueStartTimeTT" Parameter="tueStartTimeTT" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="TueEndTimeHour" Parameter="tueEndTimeHour" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="TueEndTimeMin" Parameter="tueEndTimeMin" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="TueEndTimeTT" Parameter="tueEndTimeTT" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="TueLaunchStartTimeHour" Parameter="tueLaunchStartTimeHour" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="TueLaunchStartTimeMin" Parameter="tueLaunchStartTimeMin" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="TueLaunchStartTimeTT" Parameter="tueLaunchStartTimeTT" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="TueLaunchEndTimeHour" Parameter="tueLaunchEndTimeHour" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="TueLaunchEndTimeMin" Parameter="tueLaunchEndTimeMin" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="TueLaunchEndTimeTT" Parameter="tueLaunchEndTimeTT" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="IsWednesday" Parameter="isWednesday" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="WenStartTimeHour" Parameter="wenStartTimeHour" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="WenStartTimeMin" Parameter="wenStartTimeMin" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="WenStartTimeTT" Parameter="wenStartTimeTT" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="WenEndTimeHour" Parameter="wenEndTimeHour" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="WenEndTimeMin" Parameter="wenEndTimeMin" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="WenEndTimeTT" Parameter="wenEndTimeTT" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="WenLaunchStartTimeHour" Parameter="wenLaunchStartTimeHour" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="WenLaunchStartTimeMin" Parameter="wenLaunchStartTimeMin" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="WenLaunchStartTimeTT" Parameter="wenLaunchStartTimeTT" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="WenLaunchEndTimeHour" Parameter="wenLaunchEndTimeHour" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="WenLaunchEndTimeMin" Parameter="wenLaunchEndTimeMin" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="WenLaunchEndTimeTT" Parameter="wenLaunchEndTimeTT" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="IsThursday" Parameter="isThursday" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="ThuStartTimeHour" Parameter="thuStartTimeHour" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="ThuStartTimeMin" Parameter="thuStartTimeMin" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="ThuStartTimeTT" Parameter="thuStartTimeTT" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="ThuEndTimeHour" Parameter="thuEndTimeHour" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="ThuEndTimeMin" Parameter="thuEndTimeMin" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="ThuEndTimeTT" Parameter="thuEndTimeTT" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="ThuLaunchStartTimeHour" Parameter="thuLaunchStartTimeHour" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="ThuLaunchStartTimeMin" Parameter="thuLaunchStartTimeMin" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="ThuLaunchStartTimeTT" Parameter="thuLaunchStartTimeTT" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="ThuLaunchEndTimeHour" Parameter="thuLaunchEndTimeHour" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="ThuLaunchEndTimeMin" Parameter="thuLaunchEndTimeMin" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="ThuLaunchEndTimeTT" Parameter="thuLaunchEndTimeTT" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="IsFriday" Parameter="isFriday" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="FriStartTimeHour" Parameter="friStartTimeHour" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="FriStartTimeMin" Parameter="friStartTimeMin" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="FriStartTimeTT" Parameter="friStartTimeTT" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="FriEndTimeHour" Parameter="friEndTimeHour" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="FriEndTimeMin" Parameter="friEndTimeMin" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="FriEndTimeTT" Parameter="friEndTimeTT" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="FriLaunchStartTimeHour" Parameter="friLaunchStartTimeHour" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="FriLaunchStartTimeMin" Parameter="friLaunchStartTimeMin" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="FriLaunchStartTimeTT" Parameter="friLaunchStartTimeTT" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="FriLaunchEndTimeHour" Parameter="friLaunchEndTimeHour" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="FriLaunchEndTimeMin" Parameter="friLaunchEndTimeMin" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="FriLaunchEndTimeTT" Parameter="friLaunchEndTimeTT" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="IsSaturday" Parameter="isSaturday" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="SatStartTimeHour" Parameter="satStartTimeHour" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="SatStartTimeMin" Parameter="satStartTimeMin" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="SatStartTimeTT" Parameter="satStartTimeTT" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="SatEndTimeHour" Parameter="satEndTimeHour" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="SatEndTimeMin" Parameter="satEndTimeMin" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="SatEndTimeTT" Parameter="satEndTimeTT" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="SatLaunchStartTimeHour" Parameter="satLaunchStartTimeHour" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="SatLaunchStartTimeMin" Parameter="satLaunchStartTimeMin" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="SatLaunchStartTimeTT" Parameter="satLaunchStartTimeTT" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="SatLaunchEndTimeHour" Parameter="satLaunchEndTimeHour" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="SatLaunchEndTimeMin" Parameter="satLaunchEndTimeMin" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="SatLaunchEndTimeTT" Parameter="satLaunchEndTimeTT" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
</Database>