#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unmehta.WebPortal.Data.Hospital
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="UNMehta")]
	public partial class StarOfMasterDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public StarOfMasterDataContext() : 
				base(global::Unmehta.WebPortal.Data.Properties.Settings.Default.UNMehtaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public StarOfMasterDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StarOfMasterDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StarOfMasterDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StarOfMasterDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllStarOfDetails")]
		public ISingleResult<GetAllStarOfDetailsResult> GetAllStarOfDetails([global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageId", DbType="BigInt")] System.Nullable<long> languageId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), languageId);
			return ((ISingleResult<GetAllStarOfDetailsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllStarOfAccordSubImageDetailsByAccordId")]
		public ISingleResult<GetAllStarOfAccordSubImageDetailsByAccordIdResult> GetAllStarOfAccordSubImageDetailsByAccordId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccordId", DbType="BigInt")] System.Nullable<long> accordId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageId", DbType="BigInt")] System.Nullable<long> languageId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), accordId, languageId);
			return ((ISingleResult<GetAllStarOfAccordSubImageDetailsByAccordIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertOrUpdateStarOfMaster")]
		public ISingleResult<InsertOrUpdateStarOfMasterResult> InsertOrUpdateStarOfMaster([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageId", DbType="BigInt")] System.Nullable<long> languageId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StarPageTitle", DbType="NVarChar(MAX)")] string starPageTitle, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StarPageMonthTabName", DbType="NVarChar(MAX)")] string starPageMonthTabName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StarPageWeekTabName", DbType="NVarChar(MAX)")] string starPageWeekTabName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StarAccordMonthTitle", DbType="NVarChar(MAX)")] string starAccordMonthTitle, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StarAccordWeekTitle", DbType="NVarChar(MAX)")] string starAccordWeekTitle, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="NVarChar(MAX)")] string userName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, languageId, starPageTitle, starPageMonthTabName, starPageWeekTabName, starAccordMonthTitle, starAccordWeekTitle, userName);
			return ((ISingleResult<InsertOrUpdateStarOfMasterResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertStarOfAccordSubImageDetailsByAccordId")]
		public int InsertStarOfAccordSubImageDetailsByAccordId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="StarId", DbType="BigInt")] System.Nullable<long> starId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccordId", DbType="BigInt")] System.Nullable<long> accordId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageId", DbType="BigInt")] System.Nullable<long> languageId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ImageName", DbType="NVarChar(MAX)")] string imageName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(MAX)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(MAX)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsVisible", DbType="Bit")] System.Nullable<bool> isVisible)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), starId, accordId, languageId, imageName, name, description, isVisible);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.RemoveStarOfAccordDetailsById")]
		public int RemoveStarOfAccordDetailsById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="NVarChar(MAX)")] string userName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, userName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.RemoveStarOfDetailsById")]
		public int RemoveStarOfDetailsById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="NVarChar(MAX)")] string userName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, userName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.RemoveStarOfAccordSubImageDetailsByAccordId")]
		public int RemoveStarOfAccordSubImageDetailsByAccordId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccordId", DbType="BigInt")] System.Nullable<long> accordId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageId", DbType="BigInt")] System.Nullable<long> languageId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), accordId, languageId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllStarOfAccordDetailsByStartId")]
		public ISingleResult<GetAllStarOfAccordDetailsByStartIdResult> GetAllStarOfAccordDetailsByStartId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartId", DbType="BigInt")] System.Nullable<long> startId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageId", DbType="BigInt")] System.Nullable<long> languageId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), startId, languageId);
			return ((ISingleResult<GetAllStarOfAccordDetailsByStartIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertOrUpdateStarOfAccordDetails")]
		public ISingleResult<InsertOrUpdateStarOfAccordDetailsResult> InsertOrUpdateStarOfAccordDetails([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StarId", DbType="BigInt")] System.Nullable<long> starId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LanguageId", DbType="BigInt")] System.Nullable<long> languageId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccordTitle", DbType="NVarChar(MAX)")] string accordTitle, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SequanceNo", DbType="BigInt")] System.Nullable<long> sequanceNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TypeMonthOrWeek", DbType="BigInt")] System.Nullable<long> typeMonthOrWeek, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsVisible", DbType="Bit")] System.Nullable<bool> isVisible, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="NVarChar(MAX)")] string userName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, starId, languageId, accordTitle, sequanceNo, typeMonthOrWeek, isVisible, userName);
			return ((ISingleResult<InsertOrUpdateStarOfAccordDetailsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.StarOfAccordDetailsSwap")]
		public int StarOfAccordDetailsSwap([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string cmd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(10,2)")] System.Nullable<decimal> currentColMenuLevel, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Packageid", DbType="Int")] System.Nullable<int> packageid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cmd, currentColMenuLevel, packageid);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class GetAllStarOfDetailsResult
	{
		
		private long _Id;
		
		private System.Nullable<long> _LanguageId;
		
		private System.Nullable<long> _StarId;
		
		private string _StarPageTitle;
		
		private string _StarPageMonthTabName;
		
		private string _StarPageWeekTabName;
		
		private string _StarAccordMonthTitle;
		
		private string _StarAccordWeekTitle;
		
		private bool _IsDelete;
		
		private string _CreateBy;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _UpdateBy;
		
		private System.Nullable<System.DateTime> _UpdateDate;
		
		private string _DeleteBy;
		
		private System.Nullable<System.DateTime> _DeleteDate;
		
		public GetAllStarOfDetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageId", DbType="BigInt")]
		public System.Nullable<long> LanguageId
		{
			get
			{
				return this._LanguageId;
			}
			set
			{
				if ((this._LanguageId != value))
				{
					this._LanguageId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StarId", DbType="BigInt")]
		public System.Nullable<long> StarId
		{
			get
			{
				return this._StarId;
			}
			set
			{
				if ((this._StarId != value))
				{
					this._StarId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StarPageTitle", DbType="NVarChar(MAX)")]
		public string StarPageTitle
		{
			get
			{
				return this._StarPageTitle;
			}
			set
			{
				if ((this._StarPageTitle != value))
				{
					this._StarPageTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StarPageMonthTabName", DbType="NVarChar(MAX)")]
		public string StarPageMonthTabName
		{
			get
			{
				return this._StarPageMonthTabName;
			}
			set
			{
				if ((this._StarPageMonthTabName != value))
				{
					this._StarPageMonthTabName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StarPageWeekTabName", DbType="NVarChar(MAX)")]
		public string StarPageWeekTabName
		{
			get
			{
				return this._StarPageWeekTabName;
			}
			set
			{
				if ((this._StarPageWeekTabName != value))
				{
					this._StarPageWeekTabName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StarAccordMonthTitle", DbType="NVarChar(MAX)")]
		public string StarAccordMonthTitle
		{
			get
			{
				return this._StarAccordMonthTitle;
			}
			set
			{
				if ((this._StarAccordMonthTitle != value))
				{
					this._StarAccordMonthTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StarAccordWeekTitle", DbType="NVarChar(MAX)")]
		public string StarAccordWeekTitle
		{
			get
			{
				return this._StarAccordWeekTitle;
			}
			set
			{
				if ((this._StarAccordWeekTitle != value))
				{
					this._StarAccordWeekTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDelete", DbType="Bit NOT NULL")]
		public bool IsDelete
		{
			get
			{
				return this._IsDelete;
			}
			set
			{
				if ((this._IsDelete != value))
				{
					this._IsDelete = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="NVarChar(MAX)")]
		public string CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this._CreateBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateBy", DbType="NVarChar(MAX)")]
		public string UpdateBy
		{
			get
			{
				return this._UpdateBy;
			}
			set
			{
				if ((this._UpdateBy != value))
				{
					this._UpdateBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this._UpdateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteBy", DbType="NVarChar(MAX)")]
		public string DeleteBy
		{
			get
			{
				return this._DeleteBy;
			}
			set
			{
				if ((this._DeleteBy != value))
				{
					this._DeleteBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeleteDate
		{
			get
			{
				return this._DeleteDate;
			}
			set
			{
				if ((this._DeleteDate != value))
				{
					this._DeleteDate = value;
				}
			}
		}
	}
	
	public partial class GetAllStarOfAccordSubImageDetailsByAccordIdResult
	{
		
		private long _Id;
		
		private System.Nullable<long> _StarId;
		
		private System.Nullable<long> _LanguageId;
		
		private System.Nullable<long> _AccordId;
		
		private string _ImageName;
		
		private string _Name;
		
		private string _Description;
		
		private System.Nullable<bool> _IsVisible;
		
		private bool _IsDelete;
		
		private string _CreateBy;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _UpdateBy;
		
		private System.Nullable<System.DateTime> _UpdateDate;
		
		private string _DeleteBy;
		
		private System.Nullable<System.DateTime> _DeleteDate;
		
		public GetAllStarOfAccordSubImageDetailsByAccordIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StarId", DbType="BigInt")]
		public System.Nullable<long> StarId
		{
			get
			{
				return this._StarId;
			}
			set
			{
				if ((this._StarId != value))
				{
					this._StarId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageId", DbType="BigInt")]
		public System.Nullable<long> LanguageId
		{
			get
			{
				return this._LanguageId;
			}
			set
			{
				if ((this._LanguageId != value))
				{
					this._LanguageId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccordId", DbType="BigInt")]
		public System.Nullable<long> AccordId
		{
			get
			{
				return this._AccordId;
			}
			set
			{
				if ((this._AccordId != value))
				{
					this._AccordId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageName", DbType="NVarChar(MAX)")]
		public string ImageName
		{
			get
			{
				return this._ImageName;
			}
			set
			{
				if ((this._ImageName != value))
				{
					this._ImageName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsVisible", DbType="Bit")]
		public System.Nullable<bool> IsVisible
		{
			get
			{
				return this._IsVisible;
			}
			set
			{
				if ((this._IsVisible != value))
				{
					this._IsVisible = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDelete", DbType="Bit NOT NULL")]
		public bool IsDelete
		{
			get
			{
				return this._IsDelete;
			}
			set
			{
				if ((this._IsDelete != value))
				{
					this._IsDelete = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="NVarChar(MAX)")]
		public string CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this._CreateBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateBy", DbType="NVarChar(MAX)")]
		public string UpdateBy
		{
			get
			{
				return this._UpdateBy;
			}
			set
			{
				if ((this._UpdateBy != value))
				{
					this._UpdateBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this._UpdateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteBy", DbType="NVarChar(MAX)")]
		public string DeleteBy
		{
			get
			{
				return this._DeleteBy;
			}
			set
			{
				if ((this._DeleteBy != value))
				{
					this._DeleteBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeleteDate
		{
			get
			{
				return this._DeleteDate;
			}
			set
			{
				if ((this._DeleteDate != value))
				{
					this._DeleteDate = value;
				}
			}
		}
	}
	
	public partial class InsertOrUpdateStarOfMasterResult
	{
		
		private System.Nullable<long> _RecId;
		
		private System.Nullable<long> _SubId;
		
		public InsertOrUpdateStarOfMasterResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecId", DbType="BigInt")]
		public System.Nullable<long> RecId
		{
			get
			{
				return this._RecId;
			}
			set
			{
				if ((this._RecId != value))
				{
					this._RecId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubId", DbType="BigInt")]
		public System.Nullable<long> SubId
		{
			get
			{
				return this._SubId;
			}
			set
			{
				if ((this._SubId != value))
				{
					this._SubId = value;
				}
			}
		}
	}
	
	public partial class GetAllStarOfAccordDetailsByStartIdResult
	{
		
		private long _Id;
		
		private System.Nullable<long> _StarId;
		
		private System.Nullable<long> _LanguageId;
		
		private string _AccordTitle;
		
		private System.Nullable<long> _SequanceNo;
		
		private System.Nullable<int> _TypeMonthOrWeek;
		
		private System.Nullable<bool> _IsVisible;
		
		private bool _IsDelete;
		
		private string _CreateBy;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _UpdateBy;
		
		private System.Nullable<System.DateTime> _UpdateDate;
		
		private string _DeleteBy;
		
		private System.Nullable<System.DateTime> _DeleteDate;
		
		private string _TypeDetail;
		
		public GetAllStarOfAccordDetailsByStartIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StarId", DbType="BigInt")]
		public System.Nullable<long> StarId
		{
			get
			{
				return this._StarId;
			}
			set
			{
				if ((this._StarId != value))
				{
					this._StarId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanguageId", DbType="BigInt")]
		public System.Nullable<long> LanguageId
		{
			get
			{
				return this._LanguageId;
			}
			set
			{
				if ((this._LanguageId != value))
				{
					this._LanguageId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccordTitle", DbType="NVarChar(MAX)")]
		public string AccordTitle
		{
			get
			{
				return this._AccordTitle;
			}
			set
			{
				if ((this._AccordTitle != value))
				{
					this._AccordTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SequanceNo", DbType="BigInt")]
		public System.Nullable<long> SequanceNo
		{
			get
			{
				return this._SequanceNo;
			}
			set
			{
				if ((this._SequanceNo != value))
				{
					this._SequanceNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeMonthOrWeek", DbType="Int")]
		public System.Nullable<int> TypeMonthOrWeek
		{
			get
			{
				return this._TypeMonthOrWeek;
			}
			set
			{
				if ((this._TypeMonthOrWeek != value))
				{
					this._TypeMonthOrWeek = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsVisible", DbType="Bit")]
		public System.Nullable<bool> IsVisible
		{
			get
			{
				return this._IsVisible;
			}
			set
			{
				if ((this._IsVisible != value))
				{
					this._IsVisible = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDelete", DbType="Bit NOT NULL")]
		public bool IsDelete
		{
			get
			{
				return this._IsDelete;
			}
			set
			{
				if ((this._IsDelete != value))
				{
					this._IsDelete = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="NVarChar(MAX)")]
		public string CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this._CreateBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateBy", DbType="NVarChar(MAX)")]
		public string UpdateBy
		{
			get
			{
				return this._UpdateBy;
			}
			set
			{
				if ((this._UpdateBy != value))
				{
					this._UpdateBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this._UpdateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteBy", DbType="NVarChar(MAX)")]
		public string DeleteBy
		{
			get
			{
				return this._DeleteBy;
			}
			set
			{
				if ((this._DeleteBy != value))
				{
					this._DeleteBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeleteDate
		{
			get
			{
				return this._DeleteDate;
			}
			set
			{
				if ((this._DeleteDate != value))
				{
					this._DeleteDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeDetail", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string TypeDetail
		{
			get
			{
				return this._TypeDetail;
			}
			set
			{
				if ((this._TypeDetail != value))
				{
					this._TypeDetail = value;
				}
			}
		}
	}
	
	public partial class InsertOrUpdateStarOfAccordDetailsResult
	{
		
		private System.Nullable<long> _RecId;
		
		public InsertOrUpdateStarOfAccordDetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecId", DbType="BigInt")]
		public System.Nullable<long> RecId
		{
			get
			{
				return this._RecId;
			}
			set
			{
				if ((this._RecId != value))
				{
					this._RecId = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
