<?xml version="1.0" encoding="utf-8"?><Database Name="UNMehta" Class="StentPriceMasterDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.1.159.2;Initial Catalog=UNMehta;User ID=sa" SettingsObjectName="Unmehta.WebPortal.Data.Properties.Settings" SettingsPropertyName="UNMehtaConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.GetAllStentPriceTypeMasterByLanguageId" Method="GetAllStentPriceTypeMasterByLanguageId">
    <Parameter Name="LangId" Parameter="langId" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="GetAllStentPriceTypeMasterByLanguageIdResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsVisableInQuickLink" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="StentPriceDesc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertOrUpdateSentPriceTypeMaster" Method="InsertOrUpdateSentPriceTypeMaster">
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="LanguageId" Parameter="languageId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="IsActive" Parameter="isActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsVisableInQuickLink" Parameter="isVisableInQuickLink" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="StentPriceDesc" Parameter="stentPriceDesc" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="InsertOrUpdateSentPriceTypeMasterResult">
      <Column Name="RecId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.RemoveStentPriceTypeMaster" Method="RemoveStentPriceTypeMaster">
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
</Database>