#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unmehta.WebPortal.Data.Hospital
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="UNMehta")]
	public partial class UnitMasterDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public UnitMasterDataContext() : 
				base(global::Unmehta.WebPortal.Data.Properties.Settings.Default.UNMehtaConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public UnitMasterDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UnitMasterDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UnitMasterDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UnitMasterDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllUnitMaster")]
		public ISingleResult<GetAllUnitMasterResult> GetAllUnitMaster()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetAllUnitMasterResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertOrUpdateUnitMaster")]
		public ISingleResult<InsertOrUpdateUnitMasterResult> InsertOrUpdateUnitMaster([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SpecilizationId", DbType="BigInt")] System.Nullable<long> specilizationId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LangId", DbType="BigInt")] System.Nullable<long> langId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UnitName", DbType="NVarChar(MAX)")] string unitName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="WeekNo", DbType="Int")] System.Nullable<int> weekNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartTimeHour", DbType="NVarChar(2)")] string startTimeHour, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartTimeMin", DbType="NVarChar(2)")] string startTimeMin, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartTimeTT", DbType="NVarChar(2)")] string startTimeTT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndTimeHour", DbType="NVarChar(2)")] string endTimeHour, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndTimeMin", DbType="NVarChar(2)")] string endTimeMin, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndTimeTT", DbType="NVarChar(2)")] string endTimeTT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="NVarChar(MAX)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, specilizationId, langId, unitName, weekNo, startTimeHour, startTimeMin, startTimeTT, endTimeHour, endTimeMin, endTimeTT, username, isActive);
			return ((ISingleResult<InsertOrUpdateUnitMasterResult>)(result.ReturnValue));
		}
		
		//[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.RemoveUnitMaster")]
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name= "dbo.RemoveSloteConfigMaster")]
		public int RemoveUnitMaster([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="NVarChar(MAX)")] string username)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, username);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetUnitMasterByIdAndLangId")]
		public ISingleResult<GetUnitMasterByIdAndLangIdResult> GetUnitMasterByIdAndLangId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LangId", DbType="BigInt")] System.Nullable<long> langId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, langId);
			return ((ISingleResult<GetUnitMasterByIdAndLangIdResult>)(result.ReturnValue));
		}
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name= "dbo.GetConfigUnitMasterByIdAndLangId")]
		public ISingleResult<GetUnitMasterByIdAndLangIdResult> GetConfigUnitMasterByIdAndLangId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LangId", DbType="BigInt")] System.Nullable<long> langId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, langId);
			return ((ISingleResult<GetUnitMasterByIdAndLangIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllUnitDoctorMasterById")]
		public ISingleResult<GetAllUnitDoctorMasterByIdResult> GetAllUnitDoctorMasterById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LangId", DbType="BigInt")] System.Nullable<long> langId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, langId);
			return ((ISingleResult<GetAllUnitDoctorMasterByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertUnitDoctorMaster")]
		public ISingleResult<InsertUnitDoctorMasterResult> InsertUnitDoctorMaster([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UnitDetailId", DbType="BigInt")] System.Nullable<long> unitDetailId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LangId", DbType="BigInt")] System.Nullable<long> langId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UnitId", DbType="BigInt")] System.Nullable<long> unitId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DocId", DbType="BigInt")] System.Nullable<long> docId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="NVarChar(MAX)")] string username)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), unitDetailId, langId, unitId, docId, username);
			return ((ISingleResult<InsertUnitDoctorMasterResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.RemoveUnitDoctorMaster")]
		public int RemoveUnitDoctorMaster([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="BigInt")] System.Nullable<long> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="NVarChar(MAX)")] string username)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, username);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class GetAllUnitMasterResult
	{
		
		private long _Id;
		
		private string _UnitName;
		
		private System.Nullable<long> _SpecilizationId;
		
		private string _SpecilizationName;
		
		private System.Nullable<int> _WeekNo;
		
		private string _WeekName;
		
		private string _StartTime;
		
		private string _EndTime;
		
		private string _StartTimeHour;
		
		private string _StartTimeMin;
		
		private string _StartTimeTT;
		
		private string _EndTimeHour;
		
		private string _EndTimeMin;
		
		private string _EndTimeTT;
		
		private System.Nullable<bool> _IsActive;
		
		public GetAllUnitMasterResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitName", DbType="NVarChar(MAX)")]
		public string UnitName
		{
			get
			{
				return this._UnitName;
			}
			set
			{
				if ((this._UnitName != value))
				{
					this._UnitName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpecilizationId", DbType="BigInt")]
		public System.Nullable<long> SpecilizationId
		{
			get
			{
				return this._SpecilizationId;
			}
			set
			{
				if ((this._SpecilizationId != value))
				{
					this._SpecilizationId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpecilizationName", DbType="NVarChar(MAX)")]
		public string SpecilizationName
		{
			get
			{
				return this._SpecilizationName;
			}
			set
			{
				if ((this._SpecilizationName != value))
				{
					this._SpecilizationName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeekNo", DbType="Int")]
		public System.Nullable<int> WeekNo
		{
			get
			{
				return this._WeekNo;
			}
			set
			{
				if ((this._WeekNo != value))
				{
					this._WeekNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeekName", DbType="VarChar(9)")]
		public string WeekName
		{
			get
			{
				return this._WeekName;
			}
			set
			{
				if ((this._WeekName != value))
				{
					this._WeekName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartTime", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string StartTime
		{
			get
			{
				return this._StartTime;
			}
			set
			{
				if ((this._StartTime != value))
				{
					this._StartTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndTime", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string EndTime
		{
			get
			{
				return this._EndTime;
			}
			set
			{
				if ((this._EndTime != value))
				{
					this._EndTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartTimeHour", DbType="NVarChar(2)")]
		public string StartTimeHour
		{
			get
			{
				return this._StartTimeHour;
			}
			set
			{
				if ((this._StartTimeHour != value))
				{
					this._StartTimeHour = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartTimeMin", DbType="NVarChar(2)")]
		public string StartTimeMin
		{
			get
			{
				return this._StartTimeMin;
			}
			set
			{
				if ((this._StartTimeMin != value))
				{
					this._StartTimeMin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartTimeTT", DbType="NVarChar(2)")]
		public string StartTimeTT
		{
			get
			{
				return this._StartTimeTT;
			}
			set
			{
				if ((this._StartTimeTT != value))
				{
					this._StartTimeTT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndTimeHour", DbType="NVarChar(2)")]
		public string EndTimeHour
		{
			get
			{
				return this._EndTimeHour;
			}
			set
			{
				if ((this._EndTimeHour != value))
				{
					this._EndTimeHour = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndTimeMin", DbType="NVarChar(2)")]
		public string EndTimeMin
		{
			get
			{
				return this._EndTimeMin;
			}
			set
			{
				if ((this._EndTimeMin != value))
				{
					this._EndTimeMin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndTimeTT", DbType="NVarChar(2)")]
		public string EndTimeTT
		{
			get
			{
				return this._EndTimeTT;
			}
			set
			{
				if ((this._EndTimeTT != value))
				{
					this._EndTimeTT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
	}
	
	public partial class InsertOrUpdateUnitMasterResult
	{
		
		private System.Nullable<long> _RecId;
		
		public InsertOrUpdateUnitMasterResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecId", DbType="BigInt")]
		public System.Nullable<long> RecId
		{
			get
			{
				return this._RecId;
			}
			set
			{
				if ((this._RecId != value))
				{
					this._RecId = value;
				}
			}
		}
	}
	
	public partial class GetUnitMasterByIdAndLangIdResult
	{
		
		private long _Id;
		
		private string _UnitName;
		private string _doctorid;
		
		private System.Nullable<long> _SpecilizationId;
		
		private string _SpecilizationName;
		
		private System.Nullable<int> _WeekNo;
		
		private string _WeekName;
		
		private string _StartTime;
		
		private string _EndTime;
		
		private string _StartTimeHour;
		
		private string _StartTimeMin;
		
		private string _StartTimeTT;
		
		private string _EndTimeHour;
		
		private string _EndTimeMin;
		
		private string _EndTimeTT;
		
		private System.Nullable<bool> _IsActive;
		
		public GetUnitMasterByIdAndLangIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitName", DbType="NVarChar(MAX)")]
		public string UnitName
		{
			get
			{
				return this._UnitName;
			}
			set
			{
				if ((this._UnitName != value))
				{
					this._UnitName = value;
				}
			}
		}
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage= "_doctorid", DbType="NVarChar(MAX)")]
		public string doctorid
        {
			get
			{
				return this._doctorid;
			}
			set
			{
				if ((this._doctorid != value))
				{
					this._doctorid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpecilizationId", DbType="BigInt")]
		public System.Nullable<long> SpecilizationId
		{
			get
			{
				return this._SpecilizationId;
			}
			set
			{
				if ((this._SpecilizationId != value))
				{
					this._SpecilizationId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpecilizationName", DbType="NVarChar(MAX)")]
		public string SpecilizationName
		{
			get
			{
				return this._SpecilizationName;
			}
			set
			{
				if ((this._SpecilizationName != value))
				{
					this._SpecilizationName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeekNo", DbType="Int")]
		public System.Nullable<int> WeekNo
		{
			get
			{
				return this._WeekNo;
			}
			set
			{
				if ((this._WeekNo != value))
				{
					this._WeekNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeekName", DbType="VarChar(9)")]
		public string WeekName
		{
			get
			{
				return this._WeekName;
			}
			set
			{
				if ((this._WeekName != value))
				{
					this._WeekName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartTime", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string StartTime
		{
			get
			{
				return this._StartTime;
			}
			set
			{
				if ((this._StartTime != value))
				{
					this._StartTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndTime", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string EndTime
		{
			get
			{
				return this._EndTime;
			}
			set
			{
				if ((this._EndTime != value))
				{
					this._EndTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartTimeHour", DbType="NVarChar(2)")]
		public string StartTimeHour
		{
			get
			{
				return this._StartTimeHour;
			}
			set
			{
				if ((this._StartTimeHour != value))
				{
					this._StartTimeHour = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartTimeMin", DbType="NVarChar(2)")]
		public string StartTimeMin
		{
			get
			{
				return this._StartTimeMin;
			}
			set
			{
				if ((this._StartTimeMin != value))
				{
					this._StartTimeMin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartTimeTT", DbType="NVarChar(2)")]
		public string StartTimeTT
		{
			get
			{
				return this._StartTimeTT;
			}
			set
			{
				if ((this._StartTimeTT != value))
				{
					this._StartTimeTT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndTimeHour", DbType="NVarChar(2)")]
		public string EndTimeHour
		{
			get
			{
				return this._EndTimeHour;
			}
			set
			{
				if ((this._EndTimeHour != value))
				{
					this._EndTimeHour = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndTimeMin", DbType="NVarChar(2)")]
		public string EndTimeMin
		{
			get
			{
				return this._EndTimeMin;
			}
			set
			{
				if ((this._EndTimeMin != value))
				{
					this._EndTimeMin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndTimeTT", DbType="NVarChar(2)")]
		public string EndTimeTT
		{
			get
			{
				return this._EndTimeTT;
			}
			set
			{
				if ((this._EndTimeTT != value))
				{
					this._EndTimeTT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
	}
	
	public partial class GetAllUnitDoctorMasterByIdResult
	{
		
		private long _Id;
		
		private System.Nullable<long> _UnitId;
		
		private System.Nullable<long> _LangId;
		
		private System.Nullable<long> _UnitDetailId;
		
		private System.Nullable<long> _DoctorId;
		
		private string _DoctorName;
		
		public GetAllUnitDoctorMasterByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitId", DbType="BigInt")]
		public System.Nullable<long> UnitId
		{
			get
			{
				return this._UnitId;
			}
			set
			{
				if ((this._UnitId != value))
				{
					this._UnitId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LangId", DbType="BigInt")]
		public System.Nullable<long> LangId
		{
			get
			{
				return this._LangId;
			}
			set
			{
				if ((this._LangId != value))
				{
					this._LangId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitDetailId", DbType="BigInt")]
		public System.Nullable<long> UnitDetailId
		{
			get
			{
				return this._UnitDetailId;
			}
			set
			{
				if ((this._UnitDetailId != value))
				{
					this._UnitDetailId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoctorId", DbType="BigInt")]
		public System.Nullable<long> DoctorId
		{
			get
			{
				return this._DoctorId;
			}
			set
			{
				if ((this._DoctorId != value))
				{
					this._DoctorId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoctorName", DbType="NVarChar(MAX)")]
		public string DoctorName
		{
			get
			{
				return this._DoctorName;
			}
			set
			{
				if ((this._DoctorName != value))
				{
					this._DoctorName = value;
				}
			}
		}
	}
	
	public partial class InsertUnitDoctorMasterResult
	{
		
		private System.Nullable<decimal> _RecId;
		
		public InsertUnitDoctorMasterResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecId", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> RecId
		{
			get
			{
				return this._RecId;
			}
			set
			{
				if ((this._RecId != value))
				{
					this._RecId = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
