<?xml version="1.0" encoding="utf-8"?><Database Name="UNMehta" Class="UnmicrCareerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.1.159.2;Initial Catalog=UNMehta;User ID=sa" SettingsObjectName="Unmehta.WebPortal.Data.Properties.Settings" SettingsPropertyName="UNMehtaConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.GetUnmicrCareerMasterByLanguageId" Method="GetUnmicrCareerMasterByLanguageId">
    <Parameter Name="LanguageId" Parameter="languageId" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="GetUnmicrCareerMasterByLanguageIdResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="LanguageId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="UnmicrcWhyJoinTitle" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UnmicrcWhyJoinDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UnmicrcGroveThatTitle" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UnmicrcGroveThatDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UnmicrcEmployeeCareTitle" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UnmicrcEmployeeCareDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsDelete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateBy" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeleteBy" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DeleteDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertOrUpdateUnmicrCareerMaster" Method="InsertOrUpdateUnmicrCareerMaster">
    <Parameter Name="LanguageId" Parameter="languageId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="UnmicrcWhyJoinTitle" Parameter="unmicrcWhyJoinTitle" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="UnmicrcWhyJoinDescription" Parameter="unmicrcWhyJoinDescription" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="UnmicrcGroveThatTitle" Parameter="unmicrcGroveThatTitle" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="UnmicrcGroveThatDescription" Parameter="unmicrcGroveThatDescription" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="UnmicrcEmployeeCareTitle" Parameter="unmicrcEmployeeCareTitle" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="UnmicrcEmployeeCareDescription" Parameter="unmicrcEmployeeCareDescription" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
</Database>